; This file was automatically generated by SIDdecompiler 0.8 from 'sid/ansious.sid'
; Name:      Ansious
; Author:    Geir Tjelta
; Released:  2019 Offence/Fairlight
; Subtunes:  1

                * = $1000

init            jmp le032
play            jmp le0eb
le006           .byte $01, $02, $04, $00, $07, $0e
le00c           .byte $00, $01, $02, $00
le010           .byte $03, $00
le012           .byte $01, $4d, $55, $53, $49, $43, $20, $26
                .byte $20, $50, $4c, $41, $59, $45, $52, $20
                .byte $42, $59, $20, $47, $45, $49, $52, $20
                .byte $54, $4a, $45, $4c, $54, $41, $20, $2d
le032           asl 
                asl 
                asl 
                tay 
                ldx #$a8
                lda #$00
                sta le115+1
                sta le117+1
                sta le203+1
                sta le213+1
le046           cpx #$18
                dex 
                bcs le04e
                sta $d400,X
le04e           sta leb72,X
                bne le046
                lda lec40,Y
                and #$0f
                sta le2bc+1
                lda lec41,Y
                sta $fb
                asl 
le061           lda lec3a,Y
                sta leb73,X
                sta leb75,X
                lda lec3b,Y
                sta leb74,X
                sta leb76,X
                lda le012
                beq le08e
                lda $fb
                and lec1b,X
                sta lec1d,X
                bcc le08e
                .byte $b9, $42, $ec, $9d, $75, $eb, $b9, $43
                .byte $ec, $9d, $76, $eb
le08e           iny 
                iny 
                lda lec1a,X
                tax 
                bpl le061
                inx 
                tay 
le098           iny 
                lda lec37
                beq le0a4
                lda le0d9,Y
                sta le77e,Y
le0a4           lda le00c,Y
                sta lebc8,X
                lda #$00
                sta le0eb+1,X
                sta le102+1,X
                lda #$08
                sta le2a2+1,X
                lda #$fe
                sta le2a4+1,X
                lda #$ff
                sta leb88,X
                sta lebb3,X
                sta lebc7,X
                sta lebdb,X
                lsr 
                sta leb72,X
                lda #$a0
                sta le0ec,X
                lda lec1d,X
                sta le006,Y
le0d9           lda lec1a,X
                tax 
                bpl le098
                sty le2b7+1
                sty le4f7+1
                iny 
                sty le2c2+1
                rts 
le0eb           lda #$bc
le0ec           ldy #$00
                sta $d405
le0f2           lda #$cc
                ldy #$00
                sta $d40c
le0f9           lda #$cc
                ldy #$00
                sta $d413
le100           lda #$a0
le102           ora #$0e
                sta $d406
le107           lda #$70
le109           ora #$0e
                sta $d40d
le10e           lda #$a0
le110           ora #$0e
                sta $d414
le115           ldy #$01
le117           ldx #$30
                beq le12c
                lda led42,X
                bpl le124
                bit le3af+1
                bvs le129
le124           dec le010
                beq le130
le129           jmp le1ca
le12c           jmp le203
le130           ldx #$34
                stx le117+1
                beq le12c
                ldy led43,X
                beq le185
                cpy #$04
                bcs le185
                txa 
                clc 
                adc #$04
                sta le130+1
                sty le010
                ldy #$00
                lda led40,X
                and #$0f
                cmp #$08
                and #$07
                sta $d415
                bcs le163
                sta le1ce+1
                sty le1eb+1
                sty le1f8+1
                iny 
le163           lda led40,X
                and #$f0
                sta lec2f,Y
                lda led42,X
                and #$70
                sta lec33,Y
                lda led42,X
                and #$0f
                sta lec31,Y
                lda led41,X
                bcc le1f9
                sty le1c3+1
                bcs le1c4
le185           sty le130+1
                lda led42,X
                and #$7f
                sta le010
                ldy led40,X
                cpy #$7f
                beq le19b
                cpy #$ff
                bne le1b2
le19b           sty le1d0+1
                lda led41,X
                tax 
                lsr 
                lsr 
                lsr 
                sta le1f8+1
                txa 
                and #$07
                sta le1eb+1
                ldy #$01
                bne le1ce
le1b2           lda led41,X
                sta le1c3+1
                tya 
                ldy #$00
                cmp #$f8
                bne le1c4
le1c0           lda #$01
                clc 
le1c3           adc #$00
le1c4           sta le1c0+1
                jmp le1fc
le1ca           tya 
                beq le1c0
le1ce           lda #$02
le1d0           ldx #$ff
                bmi le1e9
                clc 
                adc le1eb+1
                cmp #$08
                and #$07
                sta le1ce+1
                sta $d415
le1e2           lda #$0d
                adc le1f8+1
                jmp le1f9
le1e9           sec 
le1eb           sbc #$01
                and #$07
                sta le1ce+1
                sta $d415
                lda le1e2+1
le1f8           sbc #$03
le1f9           sta le1e2+1
le1fc           sta $d416
                sty le115+1
le203           lda #$00
                bne le20a
                lda lec2f,Y
le20a           ora #$03
                sta $d417
                sec 
                lda lec31,Y
le213           sbc #$00
                bpl le218
                .byte $a9, $00
le218           ora lec33,Y
                sta $d418
                lda le227+1
                sta $d402
le225           ldx #$f9
le227           lda #$14
                stx $d403
le22c           ldx #$fb
le22e           ldy #$20
                sty $d409
le233           ldy #$0d
le235           lda #$b0
                stx $d40a
                sta $d410
                sty $d411
                lda #$00
le242           ldx #$00
                beq le257
le246           ldy #$10
                stx $d404
                sta $d400
                sta $d401
                sty $d404
                sta le242+1
le257           ldx #$00
                beq le26c
le25b           ldy #$09
                stx $d40b
                sta $d407
                sta $d408
                sty $d40b
                sta le257+1
le26c           ldx #$00
                beq le280
le270           ldy #$00
                stx $d412
                sta $d40e
                sta $d40f
                sty $d412
                sta le26c+1
le280           lda le289+1
                sta $d400
le287           ldx #$04
le289           lda #$1b
                stx $d401
le28e           ldx #$14
le290           ldy #$b0
                sty $d407
le295           ldy #$0a
le297           lda #$59
                stx $d408
                sta $d40e
                sty $d40f
le2a2           lda #$41
le2a4           and #$ff
                sta $d404
le2a9           lda #$41
le2ab           and #$ff
                sta $d40b
le2b0           lda #$41
le2b2           and #$ff
                sta $d412
le2b7           ldy #$03
                dey 
                bpl le2d2
le2bc           ldy #$04
                cpy #$09
                bne le2cf
le2c2           lda #$00
                and #$03
                tax 
                inc le2c2+1
                lda led40,X
                and #$0f
                tay 
le2cf           sty le4f7+1
le2d2           sty le2b7+1
                lda leb33,Y
                sta le3af+1
                ldx #$00
le2dd           lda leb8d,X
                bne le2e5
                jmp le3ab
le2e5           bmi le2ff
                lda leba2,X
                cmp #$c0
                lda #$00
                ldy leb9c,X
                bne le304
                bcs le32c
                lda leb8d,X
                sta leb8c,X
                lda #$00
                beq le360
le2ff           sta le2a4+1,X
                bmi le363
le304           sta leb9c,X
                bmi le315
                lda leb9d,X
                sta lebf4,X
                lda leb9e,X
                sta lebf5,X
le315           bcs le32c
                clc 
                ldy leb8c,X
                lda leab4,Y
                adc lebc8,X
                sta lebf2,X
                lda lea54,Y
                adc #$00
                sta lebf3,X
le32c           lda leb8d,X
                sta leb9f,X
                tay 
                clc 
                lda leab4,Y
                adc lebc8,X
                sta leba0,X
                lda lea54,Y
                adc #$00
                sta leba1,X
                tay 
                lda leba0,X
                cmp lebf2,X
                tya 
                sbc lebf3,X
                ldy #$cc
                lda #$90
                bcs le359
                iny 
                lda #$b0
le359           sta lec1f,X
                tya 
                sta lebf1,X
le360           sta leba2,X
le363           lda #$00
                beq le3a8
le367           lda lee5a,Y
                and #$08
                beq le374
                lda leb8b,X
                sta le2a4+1,X
le374           jmp le4bc
                lda leb72,X
                cmp #$7f
                bne le397
                lda #<lef00
                sta leb72,X
                sta leb89,X
                sta $fb
                ldy leb73,X
                lda leb74,X
                sta $fc
                lda ($fb),Y
                bmi le3df
                jmp le3fb
le397           jmp le40c
le39a           .byte $c9, $81, $a9, $fe, $b0, $d1, $a9, $00
                .byte $9d, $a2, $e2, $9d, $1d, $ec
le3a8           sta leb8d,X
le3ab           lda lec1d,X
le3af           bne le374
                .byte $4c, $7d, $e7
                lda leb87,X
                bmi le39a
                cmp leb88,X
                bne le374
                lda leb8b,X
                sta leb8d,X
                ldy leb8a,X
                beq le374
                cmp #$fe
                lda lebb2,X
                bpl le3d7
                and #$7f
                sta lebb3,X
                sta lebb2,X
le3d7           ldy lebb4,X
                bcs le367
                jmp le787
le3df           cmp #$fe
                beq le3fb
                bcc le3ef
                ldy leb75,X
                lda leb76,X
                sta $fc
                lda ($fb),Y
le3ef           and #$7f
                sta leb77,X
                iny 
                bne le3f9
                .byte $e6, $fc
le3f9           lda ($fb),Y
le3fb           sta leb78,X
                iny 
                bne le403
                inc $fc
le403           lda $fc
                sta leb74,X
                tya 
                sta leb73,X
le40c           jmp le4bc
                dec leb87,X
                bpl le40c
                ldy leb78,X
                bmi le40c
                lda #$ff
                sta leb8a,X
                lda lf07e,Y
                sta $fb
                lda lf0cf,Y
                sta $fc
                ldy leb89,X
                lda ($fb),Y
                bpl le46e
                cmp #$a0
                bcc le45f
                asl 
                bpl le450
                sta lebb2,X
                bmi le45a
le43b           lda #$fe
                bit $ffa9
                sta leb8b,X
                iny 
                tya 
                sta leb89,X
                lda ($fb),Y
                sta leb72,X
                jmp le4b6
le450           asl 
                asl 
                sta lebb4,X
                lda #$00
                sta lebb5,X
le45a           iny 
                lda ($fb),Y
                bpl le46e
le45f           cmp #$90
                bcc le466
                inc leb8a,X
le466           and #$0f
                sta leb88,X
                iny 
                lda ($fb),Y
le46e           beq le43b
                cmp #$7e
                beq le43b+3
                adc leb77,X
                sta leb8b,X
                iny 
                tya 
                sta leb89,X
                lda ($fb),Y
                sta leb72,X
                lda leb8a,X
                beq le4b6
                ldy lebb4,X
                lda lee5a,Y
                sta $fb
                bpl le4a7
                and #$07
                sta le102+1,X
                lda $fb
                and #$20
                beq le4a2
                .byte $b9, $58, $ee, $2c
le4a2           lda #$0f
                sta le0eb+1,X
le4a7           lda #$fe
                sta le2a4+1,X
                bit $fb
                bvc le4b6
                and le2a2+1,X
                sta $d404,X
le4b6           lda leb88,X
                sta leb87,X
le4bc           ldy lebca,X
                beq le4f2
                lda le3af+1
                cmp #$c7
                bne le4f2
                lda leb87,X
                cmp leb88,X
                bne le4f2
                lda leb8b,X
                bmi le4f2
                dec lebcb,X
                bpl le4f2
                lda ledcc,Y
                sta lebb6,X
                lda ledcd,Y
                sta lebb7,X
                lda ledce,Y
                sta lebcb,X
                lda ledcf,Y
                sta lebca,X
le4f2           lda le2a4+1,X
                lsr 
le4f7           ldy #$04
                bcc le50b
                dey 
                cpy le2b7+1
                bne le50b
                lda lebc6,X
                sta le102+1,X
                lda #$a0
                sta le0ec,X
le50b           ldy lebdd,X
                lda lebdb,X
                bne le567
                lda ledcd,Y
                cmp #$fe
                bcs le54b
                lda ledcc,Y
                cmp #$f0
                bcc le55b
                lda lebb1,X
                beq le533
                dec lebb1,X
                bne le53b
                iny 
                iny 
                tya 
                sta lebdd,X
                bne le544
le533           lda ledcc,Y
                and #$0f
                sta lebb1,X
le53b           lda ledcd,Y
                sta lebdc,X
                and #$fe
                tay 
le544           lda ledcd,Y
                cmp #$fe
                bcc le55e
le54b           lsr 
                lda ledcc,Y
                sta le225+1,X
                and #$f0
                sta le227+1,X
                bcc le59c
                iny 
                iny 
le55b           lda ledcd,Y
le55e           and #$7f
                sta lebdb,X
                tya 
                sta lebdd,X
le567           lda lebdc,X
                lsr 
                bcc le572
                .byte $2c, $af, $e3, $70, $0c
le572           dec lebdb,X
                bne le57e
                tya 
                clc 
                adc #$02
                sta lebdd,X
le57e           lda ledcd,Y
                asl 
                lda le227+1,X
                bcs le591
                adc ledcc,Y
                bcc le599
                inc le225+1,X
                bcs le599
le591           sbc ledcc,Y
                bcs le599
                dec le225+1,X
le599           sta le227+1,X
le59c           ldy lec07,X
                lda lec42,Y
                cmp #$7f
                bmi le622
                bne le5b1
                lda lecc1,Y
                tay 
                lda lec42,Y
                bpl le622
le5b1           cmp #$f0
                bcc le5d7
                sta $fb
                tya 
                cmp lebdf,X
                bne le5c0
                iny 
                bne le5d4
le5c0           sta lebdf,X
                clc 
                adc lecc1,Y
                tay 
                lda $fb
                and #$0f
                sta lec08,X
                and #$07
                sta lec09,X
le5d4           lda lec42,Y
le5d7           cmp #$ef
                bne le5e6
                .byte $b9, $c1, $ec, $0a, $9d, $c7, $eb, $c8
                .byte $b9, $42, $ec
le5e6           cmp #$ed
                bne le5f9
                .byte $a9, $a9, $9d, $ec, $e0, $b9, $c1, $ec
                .byte $9d, $ed, $e0, $c8, $b9, $42, $ec
le5f9           cmp #$e0
                bcc le61b
                sty $fc
                asl 
                asl 
                asl 
                asl 
                sta $fb
                lda lecc1,Y
                and le2a4+1,X
                ldy lec1e,X
                sta le246+1,Y
                and #$01
                ora $fb
                sta le242+1,Y
                ldy $fc
                iny 
le61b           tya 
                sta lec07,X
                lda lec42,Y
le622           sta $fb
                lda lecc1,Y
                beq le62c
                sta le2a2+1,X
le62c           lda lec08,X
                beq le644
                cmp #$08
                bcc le63a
                bit le3af+1
                bvs le649
le63a           dec lec09,X
                bpl le649
                and #$07
                sta lec09,X
le644           iny 
                tya 
                sta lec07,X
le649           lda leba2,X
                beq le6b8
                cmp #$02
                bne le6bb
                ldy lec0b,X
                lda lec0a,X
                cmp leb43,Y
                bcc le664
                lda #$01
                sta lec0a,X
                bne le66b
le664           adc lec0b,X
                tay 
                inc lec0a,X
le66b           lda $fb
                bne le6b5
                lda leb44,Y
                sta $fb
                and #$7f
                cmp #$60
                bcc le67c
                ora #$80
le67c           clc 
                adc leb8c,X
                tay 
                cmp #$5f
                lda #$00
                bcc le68a
                lda le9f2+2,Y
le68a           sta $fc
                lda $fb
                asl 
                beq le694
                lda lea54,Y
le694           sta $fb
                lda lebf2,X
                bcs le6a8
                adc $fb
                sta le289+1,X
                lda lebf3,X
                adc $fc
                jmp le741
le6a8           sbc $fb
                sta le289+1,X
                lda lebf3,X
                sbc $fc
                jmp le741
le6b5           .byte $4c, $28, $e7
le6b8           jmp le726
le6bb           sta $fc
                lda leba0,X
                sta le6f7+1
                lda lebf1,X
                lsr 
                lda lebf2,X
                bcs le6da
                adc lebf4,X
                tay 
                lda lebf3,X
                adc lebf5,X
                bcc le6f2
                bcs le6e6
le6da           sbc lebf4,X
                tay 
                lda lebf3,X
                sbc lebf5,X
                bcs le6f2
le6e6           bit $fc
                bvs le705
                lda #$00
                sta leba2,X
                tay 
                beq le711
le6f2           bit $fc
                bvc le711
le6f7           cpy #$9c
                pha 
                sbc leba1,X
                lda lec1f,X
                sta le703
                pla 
le703           bcs le711
le705           lda leb9f,X
                sta leb8c,X
                ldy le6f7+1
                lda leba1,X
le711           sta lebf3,X
                tya 
                sta lebf2,X
                lda $fb
                bne le728
                tya 
                sta le289+1,X
                lda lebf3,X
                jmp le741
le726           lda $fb
le728           cmp #$81
                bcs le72f
                adc leb8c,X
le72f           and #$7f
le731           tay 
le732           clc 
                lda leab4,Y
                adc lebc8,X
                sta le289+1,X
                lda lea54,Y
                adc #$00
le741           sta le287+1,X
le744           ldy lebb3,X
                bmi le771
                lda #$ff
                sta lebb3,X
                lda lef39,Y
                sta $fc
                lda lef38,Y
                sta $fb
                and #$f0
                lsr 
                lsr 
                lsr 
                tay 
                lda leb14,Y
                sta le76f+2
                lda leb13,Y
                sta le76f+1
                lda $fb
                and #$0f
le76f           jmp lea31
le771           ldy lebc7,X
                bmi le77e
                .byte $a9, $ff, $9d, $c7, $eb, $d0, $d1
le77e           lda lec1a,X
                bmi le786
                tax 
                jmp le2dd
le786           rts 
le787           lda lee5f,Y
                sta lec07,X
                lda lee5e,Y
                sta $fc
                and #$0f
                sta lec08,X
                and #$07
                sta lec09,X
                sty $fb
                lda lee5c,Y
                bne le7ac
                lda le20a+1
                and lec1c,X
                jmp le7cc
le7ac           cmp #$03
                beq le7cf
                bcc le7c6
                bit $fc
                bpl le7bb
                .byte $bc, $b5, $eb, $d0, $0b
le7bb           sta le117+1
                sta le130+1
                lda #$01
                sta le010
le7c6           lda le20a+1
                ora lec1b,X
le7cc           sta le20a+1
le7cf           ldy lebb3,X
                bmi le811
                lda lef38,Y
                bpl le811
                cmp #$b0
                bcs le811
                sta lebb3,X
                cmp #$90
                bcc le803
                cmp #$a0
                and #$0f
                sta le7fa+1
                lda lef39,Y
                tay 
                bcs le7f4
                sta lebb7,X
le7f4           lda lebb6,X
                and #$f0
le7fa           ora #$01
                bcs le835
                sta lebb6,X
                jmp le835
le803           .byte $9d, $9c, $eb, $29, $0f, $9d, $f5, $eb
                .byte $b9, $39, $ef, $9d, $f4, $eb
le811           lda lebb5,X
                bne le82f
                sta leba2,X
                lda lebca,X
                bne le82f
                ldy $fb
                lda lee59,Y
                sta lebb7,X
                lda lee58,Y
                sta lebb6,X
                jmp le832
le82f           lda lebb6,X
le832           ldy lebb7,X
le835           sta le0eb+1,X
                tya 
                and #$0f
                sta lebc6,X
                tya 
                and #$f0
                sta le100+1,X
                lda #$0f
                sta le102+1,X
                lda #$a0
                sta le0ec,X
                ldy $fb
                lda lee5a,Y
                and #$10
                beq le866
                ldy lec1e,X
                lda #$11
                sta le242+1,Y
                lda #$09
                sta le246+1,Y
                ldy $fb
le866           lda lee5b,Y
                beq le86e
                sta le2a2+1,X
le86e           sta $fb
                lda #$00
                sta lebe1,X
                bit $fc
                bvc le889
                lda lebb5,X
                beq le889
                lda lebdc,X
                lsr 
                bcc le8b1
                .byte $de, $db, $eb, $b0, $28
le889           sta lebdb,X
                sta lebb1,X
                lda lee5d,Y
                sta lebdc,X
                and #$fe
                sta lebdd,X
                bit $fb
                bvc le8b1
                tay 
                lda ledcd,Y
                cmp #$fe
                bcc le8b1
                lda ledcc,Y
                sta le225+1,X
                and #$f0
                sta le227+1,X
le8b1           lda #$ff
                sta lebb5,X
                sta le2a4+1,X
                sta lebdf,X
                lda leba2,X
                asl 
                bmi le8e7
                lda leb9c,X
                bne le8da
                sta leba2,X
                sta leb8d,X
                lda leb8b,X
                sta leb8c,X
                ldy $fb
                beq le8e4
                jmp le731
le8da           lda $fb
                beq le8e4
                ldy leb8c,X
                jmp le732
le8e4           jmp le744
le8e7           .byte $a5, $fb, $f0, $f9, $bd, $f2, $eb, $4c
                .byte $1d, $e7, $f0, $03, $8d, $0a, $e2, $a5
                .byte $fc, $29, $f0, $8d, $03, $e2, $a5, $fc
                .byte $29, $0f, $f0, $05, $49, $0f, $8d, $13
                .byte $e2, $4c, $71, $e7
le90b           sta le2c2+1
                lda $fc
                and #$0f
                sta le2bc+1
                jmp le771
                .byte $a5, $fc, $9d, $c8, $eb, $4c, $71, $e7
le920           sta lec08,X
                lda $fc
                beq le92c
                sta lec07,X
                lda #$00
le92c           sta lec09,X
                jmp le771
le932           sta le102+1,X
                sta lebc6,X
                lda $fc
                sta le0eb+1,X
                jmp le771
le940           clc 
le941           ldy #$38
                sta $fb
                lda lebb6,X
                and #$f0
                ora $fb
                bcs le951
                sta lebb6,X
le951           sta le0eb+1,X
                lda $fc
                bcs le95b
                sta lebb7,X
le95b           and #$f0
                sta le100+1,X
                lda $fc
                and #$0f
                sta le102+1,X
                sta lebc6,X
                jmp le771
le96d           ldy leba2,X
                cpy #$c0
                bcc le97f
                .byte $9d, $f5, $eb, $a5, $fc, $9d, $f4, $eb
                .byte $98, $d0, $0a
le97f           sta leb9e,X
                lda $fc
                sta leb9d,X
                lda #$01
                sta leb9c,X
                jmp le771
                .byte $a4, $fc, $4a, $29, $04, $d0, $14, $6a
                .byte $8d, $d0, $e1, $98, $4a, $4a, $4a, $8d
                .byte $f8, $e1, $98, $29, $07, $8d, $eb, $e1
                .byte $4c, $71, $e7, $8c, $c3, $e1, $4c, $71
                .byte $e7, $9d, $25, $e2, $a5, $fc, $9d, $dc
                .byte $eb, $29, $fe, $9d, $dd, $eb, $a9, $00
                .byte $9d, $db, $eb, $9d, $27, $e2, $4c, $71
                .byte $e7
le9c8           lsr 
                lda $fc
                bcs le9d8
                .byte $9d, $e1, $eb, $a9, $00, $9d, $e0, $eb
                .byte $4c, $71, $e7
le9d8           sta lebca,X
                lda #$00
                sta lebcb,X
                jmp le771
le9e3           beq le9e8
                .byte $8d, $0a, $e2
le9e8           lda $fc
                sta le117+1
                sta le130+1
                lda #$01
le9f2           sta le010
le9f5           jmp le771
le9f8           lda #$bc
le9fa           bit $bda9
                ldy leba2,X
                cpy #$c0
                bcs le9f5
                sta lebf1,X
                sta leba2,X
                lda $fb
                and #$0f
                sta lebf5,X
                lda $fc
                sta lebf4,X
                tya 
                bne lea2e
                clc 
                ldy leb8c,X
                lda leab4,Y
                adc lebc8,X
                sta lebf2,X
                lda lea54,Y
                adc #$00
                sta lebf3,X
lea2e           jmp le771
lea31           lda $fc
                sta lec0b,X
                lda #$02
                sta leba2,X
                clc 
                ldy leb8c,X
                lda leab4,Y
                adc lebc8,X
                sta lebf2,X
                lda lea54,Y
                adc #$00
                sta lebf3,X
                jmp le771
                .byte $01
lea54           .byte $01, $01, $01, $01, $01, $01, $01, $01
                .byte $01, $01, $01, $02, $02, $02, $02, $02
                .byte $02, $02, $03, $03, $03, $03, $03, $04
                .byte $04, $04, $04, $05, $05, $05, $06, $06
                .byte $06, $07, $07, $08, $08, $09, $09, $0a
                .byte $0a, $0b, $0c, $0d, $0d, $0e, $0f, $10
                .byte $11, $12, $13, $14, $15, $17, $18, $1a
                .byte $1b, $1d, $1f, $20, $22, $24, $27, $29
                .byte $2b, $2e, $31, $34, $37, $3a, $3e, $41
                .byte $45, $49, $4e, $52, $57, $5c, $62, $68
                .byte $6e, $75, $7c, $83, $8b, $93, $9c, $a5
                .byte $af, $b9, $c4, $d0, $dd, $ea, $f8, $07
leab4           .byte $16, $27, $38, $4b, $5f, $73, $8a, $a1
                .byte $ba, $d4, $f0, $0e, $2d, $4e, $71, $96
                .byte $bd, $e7, $13, $42, $74, $a9, $e0, $1b
                .byte $5a, $9b, $e2, $2c, $7b, $ce, $27, $85
                .byte $e8, $51, $c1, $37, $b4, $37, $c4, $57
                .byte $f5, $9c, $4e, $09, $d0, $a3, $82, $6e
                .byte $68, $6e, $88, $af, $eb, $39, $9c, $13
                .byte $a1, $46, $04, $dc, $d0, $dc, $10, $5e
                .byte $d6, $72, $38, $26, $42, $8c, $08, $b8
                .byte $a0, $b8, $20, $bc, $ac, $e4, $70, $4c
                .byte $84, $18, $10, $70, $40, $70, $40, $78
                .byte $58, $c8, $e0, $98, $08, $30, $20
leb13           .byte <le9f8
leb14           .byte >le9f8, <le9e3, >le9e3, <le9fa+1, >le9fa+1, <le9c8, >le9c8, $b0
                .byte $e9, $8f, $e9, <lea31, >lea31, $31, $ea, <le96d
                .byte >le96d, <le940, >le940, <le941+1, >le941+1, <le932, >le932, <le920
                .byte >le920, $18, $e9, <le90b, >le90b, $f1, $e8
leb33           .byte $03, $c7, $5f, $c4, $c4, $c4, $c4, $c4
                .byte $c4, $c4, $c4, $c4, $c4, $c4, $c4, $c4
leb43           .byte $04
leb44           .byte $23, $00, $a3, $00, $08, $23, $17, $00
                .byte $97, $a3, $97, $00, $17, $0a, $0b, $1e
                .byte $27, $2c, $27, $1e, $0b, $8b, $9e, $8b
                .byte $0a, $1e, $17, $0b, $00, $8b, $97, $8b
                .byte $00, $0b, $17, $0a, $12, $0b, $7f, $00
                .byte $ff, $8b, $ff, $00, $7f, $0b
leb72           .byte $83
leb73           .byte $da
leb74           .byte $ef
leb75           .byte $9a
leb76           .byte $ef
leb77           .byte $08
leb78           .byte $1f, $a4, $1b, $f0, $ec, $ef, $08, $25
                .byte $c4, $68, $f0, $2d, $f0, $08, $18
leb87           .byte $06
leb88           .byte $07
leb89           .byte $07
leb8a           .byte $ff
leb8b           .byte $17
leb8c           .byte $17
leb8d           .byte $00, $00, $01, $12, $ff, $33, $33, $00
                .byte $03, $04, $0f, $ff, $27, $27, $00
leb9c           .byte $00
leb9d           .byte $10
leb9e           .byte $01
leb9f           .byte $29
leba0           .byte $9c
leba1           .byte $0b
leba2           .byte $00, $00, $80, $01, $43, $27, $34, $00
                .byte $00, $80, $01, $2e, $84, $0f, $00
lebb1           .byte $00
lebb2           .byte $1c
lebb3           .byte $91
lebb4           .byte $40
lebb5           .byte $ff
lebb6           .byte $bc
lebb7           .byte $ae, $00, $38, $ff, $48, $ff, $cc, $7e
                .byte $00, $08, $ff, $50, $ff, $cc, $ae
lebc6           .byte $0e
lebc7           .byte $ff
lebc8           .byte $00, $00
lebca           .byte $00
lebcb           .byte $00, $00, $0e, $ff, $01, $00, $00, $00
                .byte $00, $0e, $ff, $02, $00, $00, $00, $00
lebdb           .byte $0a
lebdc           .byte $50
lebdd           .byte $52, $00
lebdf           .byte $ff, $00
lebe1           .byte $00, $04, $48, $4a, $00, $ff, $00, $00
                .byte $19, $0a, $1a, $00, $ff, $00, $00, $00
lebf1           .byte $bc
lebf2           .byte $f5
lebf3           .byte $0a
lebf4           .byte $1c
lebf5           .byte $00, $00, $00, $bc, $00, $00, $40, $0f
                .byte $00, $00, $bc, $39, $09, $e0, $01, $00
                .byte $00, $00
lec07           .byte $02
lec08           .byte $00
lec09           .byte $00
lec0a           .byte $01
lec0b           .byte $05, $00, $00, $02, $00, $00, $03, $05
                .byte $00, $00, $02, $00, $00, $01, $19
lec1a           .byte $07
lec1b           .byte $01
lec1c           .byte $fe
lec1d           .byte $01
lec1e           .byte $00
lec1f           .byte $90, $00, $0e, $02, $fd, $02, $15, $b0
                .byte $04, $ff, $04, $fb, $04, $2a, $90, $08
lec2f           .byte $f0, $f0
lec31           .byte $0f, $0f
lec33           .byte $60, $30, $fc, $3c
lec37           .byte $01, $00, $00
lec3a           .byte $9a
lec3b           .byte >lef00, $ec, >lef00, $2d, >lf000
lec40           .byte $04
lec41           .byte $07
lec42           .byte $00, $00, $7f, $00, $7f, $0c, $00, $0c
                .byte $00, $00, $0c, $00, $00, $7f, $09, $00
                .byte $09, $04, $00, $7d, $78, $71, $7f, $08
                .byte $00, $08, $03, $00, $7c, $77, $74, $7f
                .byte $07, $00, $07, $04, $02, $7f, $0c, $00
                .byte $0c, $06, $03, $7f, $00, $00, $00, $f8
                .byte $00, $e8, $0c, $e8, $0c, $7f, $00, $00
                .byte $00, $7e, $7e, $7e, $7f, $07, $00, $07
                .byte $03, $00, $7c, $07, $7f, $09, $00, $09
                .byte $07, $04, $7f, $aa, $a6, $a0, $c1, $c1
                .byte $89, $7f, $09, $00, $09, $04, $00, $7d
                .byte $78, $f8, $71, $7f, $08, $00, $08, $03
                .byte $00, $7c, $77, $f8, $74, $7f, $08, $00
                .byte $08, $03, $00, $7c, $7f, $05, $07, $0a
                .byte $0c, $07, $05, $03, $7f, $05, $00, $05
                .byte $02, $00, $79, $76, $f3, $74, $7f
lecc1           .byte $00, $00, $01, $41, $03, $41, $41, $41
                .byte $41, $41, $41, $41, $41, $05, $41, $00
                .byte $00, $40, $00, $00, $00, $00, $10, $41
                .byte $00, $00, $40, $00, $00, $00, $00, $19
                .byte $41, $00, $00, $00, $40, $21, $41, $00
                .byte $00, $00, $40, $27, $11, $41, $41, $00
                .byte $20, $10, $20, $10, $20, $30, $00, $00
                .byte $00, $00, $00, $00, $36, $41, $00, $00
                .byte $00, $40, $00, $00, $40, $41, $00, $00
                .byte $00, $40, $46, $61, $41, $41, $80, $80
                .byte $54, $50, $41, $00, $00, $40, $00, $00
                .byte $00, $01, $00, $54, $41, $00, $00, $40
                .byte $00, $00, $00, $01, $00, $5e, $41, $00
                .byte $00, $40, $00, $00, $68, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $40, $00, $00, $00, $01, $00, $75
led40           .byte $04
led41           .byte $05
led42           .byte $04
led43           .byte $05, $f0, $07, $3f, $01, $f8, $01, $6f
                .byte $01, $ff, $02, $83, $10, $f8, $02, $83
                .byte $14, $7f, $02, $83, $18, $f8, $ff, $83
                .byte $1c, $ff, $02, $83, $20, $f8, $e0, $83
                .byte $24, $7f, $04, $83, $28, $f8, $20, $83
                .byte $0c, $f0, $20, $3f, $01, $ff, $19, $08
                .byte $34, $ff, $02, $02, $38, $ff, $01, $03
                .byte $3c, $7f, $11, $83, $40, $ff, $12, $82
                .byte $3c, $f0, $0c, $1f, $03, $ff, $11, $04
                .byte $4c, $ff, $01, $0e, $50, $7f, $01, $20
                .byte $54, $ff, $01, $20, $58, $7f, $01, $13
                .byte $4c, $60, $30, $3f, $01, $ff, $3e, $03
                .byte $64, $7f, $02, $83, $68, $ff, $0b, $82
                .byte $6c, $7f, $0d, $82, $70, $7f, $00, $81
                .byte $68, $f0, $20, $1f, $01, $f8, $01, $6f
                .byte $01, $ff, $39, $81, $80, $7f, $0d, $81
                .byte $84, $7f, $21, $81, $88, $f8, $02, $83
                .byte $14
ledcc           .byte $08
ledcd           .byte $fe
ledce           .byte $00
ledcf           .byte $fe, $8d, $ff, $b0, $87, $60, $84, $05
                .byte $84, $02, $82, $f4, $0a, $20, $81, $b0
                .byte $82, $04, $ff, $80, $02, $50, $20, $30
                .byte $a0, $f0, $04, $00, $00, $06, $ff, $90
                .byte $02, $40, $02, $60, $02, $08, $ff, $40
                .byte $85, $04, $83, $f0, $28, $08, $ff, $20
                .byte $02, $10, $02, $08, $02, $06, $02, $04
                .byte $02, $06, $02, $08, $02, $10, $02, $f4
                .byte $32, $20, $a0, $f0, $32, $ff, $ff, $b0
                .byte $8b, $4a, $8a, $78, $01, $50, $16, $50
                .byte $96, $40, $14, $40, $94, $f0, $50, $00
                .byte $00, $36, $57, $00, $60, $56, $69, $00
                .byte $64, $36, $48, $00, $68, $67, $79, $00
                .byte $5c, $50, $ff, $80, $07, $90, $0b, $94
                .byte $8b, $f0, $70, $00, $00, $01, $ff, $50
                .byte $04, $30, $04, $10, $08, $20, $08, $30
                .byte $04, $40, $08, $08, $40, $17, $c0, $f0
                .byte $7e
lee58           .byte $00
lee59           .byte $5a
lee5a           .byte $10
lee5b           .byte $11
lee5c           .byte $00
lee5d           .byte $20
lee5e           .byte $00
lee5f           .byte $2c, $0b, $e9, $58, $11, $00, $04, $40
                .byte $03, $0a, $b9, $58, $09, $04, $30, $08
                .byte $05, $07, $7a, $10, $41, $00, $20, $00
                .byte $0e, $07, $7a, $10, $41, $00, $20, $00
                .byte $17, $07, $7a, $10, $41, $00, $20, $00
                .byte $20, $07, $7a, $10, $41, $00, $20, $00
                .byte $26, $db, $be, $48, $41, $00, $78, $40
                .byte $03, $bc, $ae, $48, $41, $2c, $48, $40
                .byte $00, $cc, $7e, $48, $41, $01, $48, $40
                .byte $00, $cc, $ae, $48, $41, $00, $04, $40
                .byte $00, $dc, $ae, $48, $41, $00, $48, $00
                .byte $00, $f0, $77, $48, $11, $00, $00, $00
                .byte $36, $06, $6a, $10, $00, $00, $20, $00
                .byte $2c, $00, $5a, $10, $11, $00, $20, $00
                .byte $2c, $c0, $7e, $00, $41, $00, $6c, $40
                .byte $00, $b9, $7c, $58, $41, $01, $48, $40
                .byte $00, $dc, $ae, $10, $21, $44, $48, $40
                .byte $03, $0c, $c9, $58, $09, $74, $30, $08
                .byte $05, $07, $7a, $10, $41, $00, $20, $00
                .byte $3d, $07, $7a, $10, $41, $00, $20, $00
                .byte $45
lef00           .byte $94, $79, $48, $11, $00, $00, $00, $00
                .byte $bc, $ae, $48, $41, $5c, $48, $40, $00
                .byte $07, $7b, $10, $41, $00, $20, $00, $52
                .byte $07, $7b, $10, $41, $00, $20, $00, $5c
                .byte $07, $7a, $10, $41, $00, $20, $00, $66
                .byte $0a, $da, $92, $00, $00, $04, $00, $03
                .byte $07, $7b, $10, $41, $00, $20, $00, $75
lef38           .byte $b2
lef39           .byte $ff, $21, $40, $60, $05, $60, $0e, $60
                .byte $19, $60, $24, $20, $1c, $00, $1c, $81
                .byte $10, $00, $80, $00, $d0, $ba, $b0, $60
                .byte $00, $91, $7a, $91, $8a, $b8, $ac, $a0
                .byte $aa, $a0, $8a, $a0, $7a, $ab, $eb, $e0
                .byte $04, $e0, $05, $e0, $07, $10, $2c, $80
                .byte $40, $80, $20, $e0, $09, $31, $5c, $31
                .byte $00, $b0, $c0, $b9, $a0, $90, $7e, $90
                .byte $5e, $bd, $f0, $e0, $06, $bb, $c0, $a2
                .byte $9a, $81, $80, $83, $c0, $01, $e0, $0f
                .byte $40, $a1, $3b, $b9, $90, $e0, $08, $20
                .byte $38, $c0, $01, $b9, $00, $10, $2c, $c2
                .byte $6e, $8c, $0c, $0f, $0b, $3d, $3e, $3d
                .byte $3e, $80, $1c, $82, $1c, $83, $1c, $82
                .byte $1a, $80, $1c, $82, $1c, $80, $1c, $83
                .byte $1b, $8c, $42, $01, $04, $01, $04, $01
                .byte $3b, $41, $01, $04, $01, $04, $01, $04
                .byte $01, $1d, $8d, $16, $21, $84, $16, $87
                .byte $21, $16, $21, $81, $3a, $85, $1e, $88
                .byte $09, $09, $80, $22, $88, $23, $26, $1e
                .byte $1f, $31, $32, $31, $36, $8d, $42, $01
                .byte $04, $01, $04, $01, $3b, $41, $12, $42
                .byte $48, $15, $ff, $8c, $0d, $10, $0a, $3f
                .byte $05, $3f, $05, $1e, $1f, $43, $02, $05
                .byte $4f, $05, $02, $3c, $09, $02, $05
lf000           .byte $4d, $4e, $50, $4e, $50, $20, $98, $20
                .byte $20, $8c, $20, $8d, $19, $19, $19, $19
                .byte $19, $19, $2c, $88, $3f, $3f, $3f, $38
                .byte $38, $24, $25, $2f, $30, $35, $37, $8d
                .byte $43, $02, $4e, $50, $4e, $50, $3c, $09
                .byte $13, $43, $49, $15, $ff, $8c, $0e, $11
                .byte $09, $03, $06, $07, $08, $17, $18, $44
                .byte $03, $06, $03, $2a, $80, $07, $8c, $45
                .byte $0a, $80, $46, $4a, $4b, $4c, $8c, $03
                .byte $2a, $80, $07, $8c, $2b, $98, $2b, $8c
                .byte $2b, $80, $2b, $8d, $29, $21, $81, $29
                .byte $21, $8d, $29, $47, $39, $80, $28, $82
                .byte $27, $88, $18, $17, $18, $17, $17, $18
                .byte $2d, $2e, $33, $34, $8d, $44, $03, $06
                .byte $03, $2a, $81, $07, $8d, $40, $0a, $14
                .byte $44, $86, $49, $8d, $15, $ff
lf07e           .byte $20, <lf123, <lf15c, <lf197, <lf1c3, <lf203, <lf23d, <lf264
                .byte <lf29e, <lf2d9, <lf2ed, <lf305, <lf315, <lf348, <lf381, <lf3b1
                .byte <lf3e8, <lf417, <lf437, <lf451, <lf469, <lf486, <lf494, <lf4a2
                .byte <lf4d3, <lf505, <lf50f, <lf524, <lf534, <lf544, <lf55f, <lf575
                .byte <lf592, <lf5a1, <lf5a6, <lf5c1, <lf5fc, <lf63c, <lf686, <lf6cf
                .byte <lf705, <lf70f, <lf722, <lf748, <lf75d, <lf779, <lf79d, <lf7c1
                .byte <lf7e8, <lf818, <lf839, <lf861, <lf895, <lf8cc, <lf909, <lf925
                .byte <lf948, <lf97f, <lf9a6, <lf9b8, <lf9df, <lfa23, <lfa31, <lfa40
                .byte <lfa78, <lfab7, <lfacc, <lfad4, <lfad9, <lfae0, <lfb25, <lfb5f
                .byte <lfb77, <lfb8e, <lfb9d, <lfbdd, <lfc0e, <lfc5a, <lfc97, <lfcd5
                .byte <lfd15
lf0cf           .byte $f1, >lf123, >lf15c, >lf197, >lf1c3, >lf203, >lf23d, >lf264
                .byte >lf29e, >lf2d9, >lf2ed, >lf305, >lf315, >lf348, >lf381, >lf3b1
                .byte >lf3e8, >lf417, >lf437, >lf451, >lf469, >lf486, >lf494, >lf4a2
                .byte >lf4d3, >lf505, >lf50f, >lf524, >lf534, >lf544, >lf55f, >lf575
                .byte >lf592, >lf5a1, >lf5a6, >lf5c1, >lf5fc, >lf63c, >lf686, >lf6cf
                .byte >lf705, >lf70f, >lf722, >lf748, >lf75d, >lf779, >lf79d, >lf7c1
                .byte >lf7e8, >lf818, >lf839, >lf861, >lf895, >lf8cc, >lf909, >lf925
                .byte >lf948, >lf97f, >lf9a6, >lf9b8, >lf9df, >lfa23, >lfa31, >lfa40
                .byte >lfa78, >lfab7, >lfacc, >lfad4, >lfad9, >lfae0, >lfb25, >lfb5f
                .byte >lfb77, >lfb8e, >lfb9d, >lfbdd, >lfc0e, >lfc5a, >lfc97, >lfcd5
                .byte >lfd15, $80, $00, $7f
lf123           .byte $a2, $80, $08, $b2, $08, $a2, $83, $08
                .byte $81, $08, $83, $0a, $b2, $81, $0a, $a2
                .byte $85, $05, $81, $05, $05, $b2, $03, $a2
                .byte $83, $05, $81, $03, $80, $08, $b2, $08
                .byte $a2, $81, $08, $08, $b2, $0a, $a2, $83
                .byte $03, $81, $05, $85, $03, $a2, $81, $03
                .byte $05, $b2, $07, $a2, $03, $08, $b2, $07
                .byte $7f
lf15c           .byte $b7, $83, $20, $81, $20, $80, $20, $20
                .byte $83, $20, $81, $20, $ac, $82, $35, $f0
                .byte $81, $7e, $80, $35, $b7, $81, $20, $20
                .byte $20, $20, $80, $20, $20, $81, $20, $b8
                .byte $83, $1f, $81, $1f, $1f, $83, $1f, $ad
                .byte $81, $1d, $b8, $83, $1f, $80, $1f, $1f
                .byte $81, $1f, $1f, $1f, $1f, $80, $1f, $1f
                .byte $81, $1f, $7f
lf197           .byte $a1, $85, $18, $c3, $81, $7e, $94, $1d
                .byte $c3, $82, $7e, $c2, $80, $7e, $81, $00
                .byte $90, $1d, $cb, $83, $7e, $81, $1f, $80
                .byte $20, $c4, $84, $7e, $81, $1f, $1b, $16
                .byte $86, $13, $c2, $83, $7e, $88, $00, $81
                .byte $0f, $14, $13, $7f
lf1c3           .byte $a2, $80, $0d, $b2, $0d, $a2, $81, $0d
                .byte $05, $b2, $08, $a2, $83, $01, $81, $01
                .byte $b2, $83, $08, $a2, $81, $01, $b2, $01
                .byte $a2, $03, $05, $01, $b2, $08, $a2, $01
                .byte $80, $0f, $b2, $0f, $a2, $81, $0f, $07
                .byte $b2, $05, $a2, $83, $03, $a2, $81, $07
                .byte $b2, $83, $0f, $a2, $81, $03, $b2, $03
                .byte $a2, $0a, $07, $b2, $05, $93, $03, $7f
lf203           .byte $a4, $83, $1d, $81, $1d, $80, $1d, $1d
                .byte $83, $1d, $81, $1d, $83, $1d, $80, $1d
                .byte $1d, $81, $1d, $1d, $80, $1d, $1d, $81
                .byte $1d, $80, $1d, $1d, $81, $1d, $83, $1f
                .byte $81, $1f, $1f, $83, $1f, $81, $1f, $83
                .byte $1f, $80, $1f, $1f, $81, $1f, $1f, $80
                .byte $1f, $1f, $81, $1f, $80, $1f, $1f, $81
                .byte $1f, $7f
lf23d           .byte $83, $11, $c2, $7e, $84, $19, $c2, $83
                .byte $7e, $82, $00, $83, $1b, $1d, $90, $19
                .byte $00, $20, $00, $81, $1f, $1b, $16, $84
                .byte $22, $c3, $7e, $85, $00, $81, $1b, $22
                .byte $27, $2b, $c2, $80, $7e, $00, $7f
lf264           .byte $a1, $80, $2c, $d3, $00, $91, $2b, $91
                .byte $29, $cb, $85, $24, $c3, $83, $7e, $c2
                .byte $81, $7e, $88, $00, $e3, $83, $30, $80
                .byte $00, $cb, $82, $30, $c3, $7e, $90, $2e
                .byte $90, $2c, $92, $2e, $c3, $7e, $90, $2c
                .byte $90, $2b, $93, $27, $c2, $84, $7e, $80
                .byte $00, $cb, $81, $27, $91, $29, $90, $2b
                .byte $00, $7f
lf29e           .byte $e4, $80, $2c, $82, $00, $de, $80, $00
                .byte $cb, $83, $7e, $81, $00, $80, $7e, $aa
                .byte $33, $ca, $7e, $93, $35, $c2, $89, $7e
                .byte $de, $80, $7e, $82, $00, $e3, $85, $2e
                .byte $c3, $80, $7e, $e1, $7e, $85, $00, $90
                .byte $2c, $90, $2b, $90, $27, $83, $7e, $c3
                .byte $85, $7e, $de, $80, $7e, $82, $00, $d5
                .byte $80, $00, $7f
lf2d9           .byte $a0, $83, $38, $35, $2c, $29, $cd, $38
                .byte $35, $2c, $29, $ce, $38, $35, $81, $2c
                .byte $2b, $29, $24, $7f
lf2ed           .byte $81, $00, $ae, $83, $37, $30, $2b, $24
                .byte $37, $30, $2b, $24, $37, $30, $b9, $80
                .byte $18, $00, $18, $18, $18, $a1, $00, $7f
lf305           .byte $a2, $8f, $01, $7e, $89, $7e, $d5, $80
                .byte $7e, $a1, $7e, $cf, $81, $18, $00, $7f
lf315           .byte $a8, $80, $11, $d4, $82, $7e, $83, $00
                .byte $80, $7e, $82, $00, $93, $0c, $80, $11
                .byte $86, $00, $80, $7e, $82, $00, $93, $0c
                .byte $80, $11, $86, $00, $80, $11, $82, $00
                .byte $80, $0c, $82, $00, $80, $11, $86, $00
                .byte $80, $11, $82, $00, $80, $0c, $00, $c8
                .byte $81, $00, $7f
lf348           .byte $a9, $80, $2c, $c5, $83, $7e, $8a, $00
                .byte $91, $29, $93, $22, $91, $24, $90, $28
                .byte $7e, $81, $00, $90, $28, $7e, $81, $00
                .byte $90, $28, $7e, $81, $00, $93, $26, $93
                .byte $28, $90, $26, $81, $7e, $80, $00, $93
                .byte $27, $90, $22, $7e, $81, $00, $90, $24
                .byte $7e, $81, $00, $90, $22, $7e, $81, $00
                .byte $7f
lf381           .byte $aa, $85, $29, $c4, $87, $00, $80, $7e
                .byte $00, $91, $2c, $93, $2b, $91, $2c, $90
                .byte $2e, $c4, $82, $7e, $91, $2c, $91, $2b
                .byte $82, $00, $c4, $8a, $00, $80, $7e, $00
                .byte $90, $2c, $7e, $c4, $81, $7e, $93, $2b
                .byte $93, $29, $91, $27, $80, $00, $7e, $7f
lf3b1           .byte $80, $1d, $81, $00, $c3, $84, $00, $80
                .byte $18, $82, $00, $80, $11, $82, $00, $83
                .byte $0d, $90, $0c, $c2, $82, $7e, $93, $0d
                .byte $93, $0f, $81, $0f, $85, $00, $80, $0f
                .byte $82, $00, $80, $0f, $82, $00, $80, $0c
                .byte $82, $00, $d5, $83, $00, $80, $0c, $82
                .byte $00, $d6, $00, $da, $80, $00, $7f
lf3e8           .byte $91, $21, $85, $00, $90, $22, $7e, $81
                .byte $00, $90, $24, $7e, $81, $00, $90, $1d
                .byte $7e, $81, $00, $90, $20, $7e, $81, $00
                .byte $90, $1d, $82, $7e, $93, $1f, $91, $22
                .byte $85, $00, $81, $22, $85, $00, $81, $20
                .byte $85, $00, $81, $1b, $85, $00, $7f
lf417           .byte $93, $29, $c4, $8b, $7e, $83, $25, $93
                .byte $24, $93, $25, $91, $27, $84, $00, $c4
                .byte $88, $00, $90, $31, $82, $7e, $93, $30
                .byte $93, $2e, $93, $2c, $91, $2b, $00, $7f
lf437           .byte $87, $00, $ab, $80, $11, $d6, $81, $7e
                .byte $8f, $00, $00, $00, $86, $00, $80, $7e
                .byte $e3, $7e, $ea, $7e, $d4, $7e, $cf, $81
                .byte $00, $7f
lf451           .byte $87, $00, $ab, $82, $20, $8f, $00, $00
                .byte $00, $86, $00, $80, $7e, $e3, $7e, $ea
                .byte $81, $7e, $cf, $80, $00, $c0, $00, $7f
lf469           .byte $88, $00, $ac, $8f, $24, $e1, $89, $00
                .byte $ed, $83, $00, $c4, $8f, $00, $8a, $00
                .byte $80, $7e, $e3, $7e, $ea, $81, $7e, $cf
                .byte $80, $00, $c0, $00, $7f
lf486           .byte $d4, $80, $00, $de, $84, $00, $cf, $8f
                .byte $00, $00, $00, $89, $00, $7f
lf494           .byte $b1, $80, $09, $da, $84, $7e, $c2, $80
                .byte $7e, $8f, $00, $88, $00, $7f
lf4a2           .byte $aa, $84, $1d, $c4, $80, $7e, $83, $00
                .byte $81, $18, $91, $20, $91, $1d, $83, $1f
                .byte $c4, $80, $7e, $84, $00, $81, $1b, $91
                .byte $22, $91, $1f, $83, $20, $c4, $80, $7e
                .byte $84, $00, $81, $18, $91, $22, $91, $24
                .byte $83, $22, $93, $1f, $93, $1c, $93, $18
                .byte $7f
lf4d3           .byte $aa, $84, $1d, $c4, $82, $7e, $81, $00
                .byte $1d, $91, $20, $91, $1d, $84, $1f, $c4
                .byte $82, $7e, $81, $00, $1b, $91, $22, $91
                .byte $1f, $84, $20, $c4, $82, $7e, $81, $00
                .byte $20, $91, $22, $91, $20, $84, $24, $c4
                .byte $81, $7e, $80, $00, $7e, $00, $c2, $85
                .byte $00, $7f
lf505           .byte $e9, $87, $34, $e9, $38, $e9, $44, $e9
                .byte $38, $7f
lf50f           .byte $a9, $82, $29, $83, $00, $e2, $80, $00
                .byte $d5, $82, $00, $e2, $80, $00, $d5, $82
                .byte $00, $e2, $80, $00, $7f
lf524           .byte $b6, $80, $29, $e2, $7e, $83, $00, $d5
                .byte $81, $00, $92, $28, $d6, $84, $00, $7f
lf534           .byte $a9, $80, $29, $d6, $81, $7e, $d5, $84
                .byte $00, $da, $82, $00, $d5, $84, $00, $7f
lf544           .byte $b1, $8f, $19, $92, $25, $c2, $84, $7e
                .byte $87, $00, $80, $16, $88, $00, $d5, $83
                .byte $00, $80, $14, $13, $0f, $8a, $00, $e2
                .byte $83, $00, $7f
lf55f           .byte $a8, $87, $0d, $83, $0d, $08, $87, $0f
                .byte $83, $0f, $07, $87, $11, $83, $11, $10
                .byte $87, $0c, $83, $07, $13, $7f
lf575           .byte $87, $19, $83, $0d, $08, $87, $0f, $83
                .byte $1b, $0c, $87, $18, $83, $18, $80, $20
                .byte $c3, $82, $7e, $80, $1c, $86, $00, $e0
                .byte $80, $1c, $86, $00, $7f
lf592           .byte $a0, $81, $38, $e9, $83, $30, $91, $35
                .byte $2c, $e9, $83, $2b, $91, $35, $7f
lf5a1           .byte $c2, $8f, $00, $00, $7f
lf5a6           .byte $aa, $81, $1c, $82, $00, $c6, $00, $a8
                .byte $80, $10, $86, $00, $aa, $82, $20, $81
                .byte $00, $c6, $82, $00, $a8, $14, $00, $80
                .byte $20, $00, $7f
lf5c1           .byte $a8, $81, $20, $00, $1d, $00, $14, $00
                .byte $11, $00, $ce, $83, $0c, $81, $18, $00
                .byte $0c, $ce, $80, $1f, $00, $a8, $81, $1b
                .byte $80, $11, $00, $14, $82, $00, $93, $0f
                .byte $a8, $81, $0c, $00, $08, $82, $10, $80
                .byte $00, $ce, $0c, $00, $0c, $00, $0c, $00
                .byte $0c, $00, $0c, $ce, $00, $0c, $0c, $a8
                .byte $13, $00, $7f
lf5fc           .byte $a3, $83, $20, $81, $20, $80, $20, $20
                .byte $81, $20, $a9, $29, $a3, $20, $83, $22
                .byte $a4, $80, $1f, $1f, $81, $1f, $1f, $a3
                .byte $22, $20, $80, $22, $22, $81, $22, $a4
                .byte $24, $a9, $2c, $a4, $24, $80, $24, $24
                .byte $81, $24, $24, $a3, $22, $a4, $1f, $a9
                .byte $2e, $a4, $80, $1f, $1f, $81, $1f, $1f
                .byte $1f, $1f, $80, $1f, $1f, $81, $1f, $7f
lf63c           .byte $a3, $83, $20, $81, $20, $80, $20, $20
                .byte $81, $20, $a9, $29, $a3, $20, $a4, $1f
                .byte $a9, $2b, $a4, $80, $1f, $1f, $81, $1f
                .byte $1f, $80, $1f, $1f, $81, $1f, $80, $1d
                .byte $1d, $81, $1d, $a3, $83, $1b, $81, $1b
                .byte $80, $1b, $1b, $83, $1b, $81, $1b, $80
                .byte $1b, $d5, $7e, $a3, $20, $20, $d6, $81
                .byte $20, $20, $80, $20, $20, $a3, $1f, $eb
                .byte $7e, $a9, $81, $1f, $00, $80, $7e, $d5
                .byte $7e, $7f
lf686           .byte $81, $18, $80, $00, $c7, $00, $90, $1d
                .byte $7e, $cc, $81, $00, $1f, $cc, $00, $14
                .byte $00, $ce, $82, $0c, $a8, $80, $7e, $cc
                .byte $18, $82, $00, $81, $0c, $80, $14, $00
                .byte $18, $00, $0c, $00, $ce, $20, $c2, $82
                .byte $7e, $a8, $81, $1b, $00, $0c, $00, $11
                .byte $a8, $82, $13, $80, $00, $ce, $14, $00
                .byte $a8, $14, $00, $82, $16, $80, $00, $ce
                .byte $16, $00, $a8, $81, $18, $80, $0c, $00
                .byte $7f
lf6cf           .byte $a0, $80, $44, $cd, $82, $38, $80, $41
                .byte $82, $35, $80, $38, $82, $2c, $80, $35
                .byte $82, $29, $ce, $80, $44, $82, $38, $80
                .byte $41, $82, $35, $80, $38, $82, $2c, $80
                .byte $35, $82, $29, $80, $44, $82, $38, $80
                .byte $41, $82, $35, $ad, $80, $38, $2c, $37
                .byte $2b, $35, $29, $24, $20, $7f
lf705           .byte $ad, $83, $38, $35, $81, $2c, $2b, $29
                .byte $24, $7f
lf70f           .byte $e7, $80, $41, $90, $44, $c2, $00, $af
                .byte $8c, $00, $80, $7e, $8c, $00, $90, $45
                .byte $90, $44, $7f
lf722           .byte $a1, $83, $11, $c2, $7e, $19, $c3, $82
                .byte $7e, $84, $00, $83, $1b, $1d, $90, $19
                .byte $00, $81, $20, $1f, $1b, $16, $85, $22
                .byte $c3, $82, $7e, $86, $00, $81, $1b, $22
                .byte $27, $82, $18, $80, $00, $7f
lf748           .byte $e9, $80, $29, $c2, $82, $00, $a0, $81
                .byte $35, $e9, $83, $30, $91, $38, $29, $e9
                .byte $80, $24, $af, $7e, $7f
lf75d           .byte $a0, $83, $38, $35, $ad, $40, $37, $cd
                .byte $38, $81, $33, $af, $80, $7e, $db, $7e
                .byte $81, $46, $90, $3f, $00, $4a, $00, $e8
                .byte $00, $dc, $00, $7f
lf779           .byte $aa, $83, $25, $24, $da, $22, $20, $85
                .byte $1f, $c4, $81, $7e, $84, $00, $82, $7e
                .byte $d4, $83, $24, $d5, $22, $20, $1f, $81
                .byte $1d, $83, $00, $c4, $85, $00, $d4, $82
                .byte $00, $80, $7e, $7f
lf79d           .byte $d5, $83, $25, $24, $da, $22, $20, $1f
                .byte $20, $22, $1b, $d5, $87, $24, $c4, $80
                .byte $7e, $84, $00, $d6, $81, $00, $e1, $84
                .byte $24, $c4, $80, $7e, $84, $00, $83, $7e
                .byte $d4, $80, $7e, $7f
lf7c1           .byte $aa, $84, $1d, $c4, $82, $7e, $81, $00
                .byte $19, $91, $1d, $91, $19, $86, $1b, $83
                .byte $00, $84, $7e, $1d, $c4, $82, $7e, $81
                .byte $00, $18, $91, $1c, $91, $1b, $19, $82
                .byte $00, $c4, $89, $00, $80, $7e, $7f
lf7e8           .byte $a7, $84, $1d, $c4, $80, $7e, $83, $00
                .byte $81, $19, $91, $1d, $91, $19, $87, $1b
                .byte $83, $1f, $81, $1f, $91, $18, $83, $20
                .byte $c4, $80, $7e, $83, $00, $80, $7e, $81
                .byte $1d, $91, $22, $90, $1d, $00, $e1, $83
                .byte $1f, $c4, $81, $7e, $84, $00, $7e, $7f
lf818           .byte $ba, $87, $0d, $83, $11, $0d, $86, $0f
                .byte $84, $00, $a8, $83, $11, $11, $81, $18
                .byte $00, $83, $11, $10, $87, $0d, $81, $00
                .byte $80, $7e, $a8, $81, $14, $00, $80, $7e
                .byte $7f
lf839           .byte $a8, $81, $19, $c2, $83, $7e, $81, $00
                .byte $83, $14, $08, $87, $0f, $83, $0f, $93
                .byte $13, $89, $18, $91, $18, $ce, $80, $20
                .byte $c2, $81, $7e, $80, $00, $e1, $1c, $c2
                .byte $84, $7e, $00, $80, $7e, $83, $18, $7f
lf861           .byte $b0, $80, $29, $ef, $81, $7e, $80, $00
                .byte $2b, $ef, $82, $7e, $80, $2c, $ef, $82
                .byte $7e, $80, $29, $ef, $7e, $81, $00, $90
                .byte $2b, $82, $7e, $c4, $83, $7e, $87, $00
                .byte $83, $30, $80, $2e, $00, $90, $30, $90
                .byte $2e, $83, $2c, $2b, $85, $29, $c4, $80
                .byte $7e, $88, $00, $7f
lf895           .byte $80, $29, $ef, $81, $7e, $80, $00, $82
                .byte $2b, $80, $00, $2c, $c4, $81, $7e, $80
                .byte $00, $29, $ef, $82, $7e, $2b, $80, $00
                .byte $90, $27, $d5, $82, $7e, $92, $22, $e2
                .byte $80, $7e, $92, $1f, $d6, $80, $7e, $85
                .byte $1d, $c4, $80, $7e, $8e, $00, $c4, $83
                .byte $00, $80, $7e, $d5, $84, $7e, $7f
lf8cc           .byte $a3, $83, $20, $81, $20, $80, $20, $20
                .byte $81, $20, $a9, $29, $a3, $20, $a4, $83
                .byte $1f, $80, $1f, $1f, $81, $1f, $1f, $a4
                .byte $1f, $1f, $80, $1f, $1f, $81, $1f, $1f
                .byte $a9, $20, $a4, $24, $80, $24, $24, $81
                .byte $24, $24, $24, $b3, $80, $1d, $1d, $83
                .byte $1d, $81, $1d, $1d, $a4, $1d, $1d, $80
                .byte $1d, $1d, $81, $1d, $7f
lf909           .byte $ba, $83, $19, $14, $0d, $93, $08, $b6
                .byte $0f, $90, $1f, $82, $00, $93, $1b, $93
                .byte $0c, $80, $11, $8e, $00, $80, $05, $88
                .byte $00, $85, $7e, $7f
lf925           .byte $b7, $83, $20, $b8, $81, $1d, $80, $1d
                .byte $1d, $b7, $81, $20, $a9, $29, $b7, $20
                .byte $80, $20, $20, $aa, $83, $22, $87, $18
                .byte $80, $18, $82, $00, $9f, $24, $89, $00
                .byte $85, $7e, $7f
lf948           .byte $a3, $83, $20, $81, $20, $80, $20, $20
                .byte $83, $20, $81, $20, $83, $20, $b4, $80
                .byte $1b, $1b, $81, $1b, $1b, $1b, $1b, $80
                .byte $1b, $1b, $81, $1b, $a5, $83, $20, $81
                .byte $20, $20, $83, $20, $81, $20, $a6, $83
                .byte $1c, $80, $1c, $1c, $81, $1c, $1c, $1c
                .byte $1c, $80, $1c, $1c, $81, $1c, $7f
lf97f           .byte $d5, $81, $00, $af, $80, $00, $db, $00
                .byte $3c, $82, $00, $c2, $81, $43, $d4, $00
                .byte $80, $40, $82, $00, $c2, $81, $42, $00
                .byte $80, $3f, $82, $00, $c2, $81, $41, $00
                .byte $80, $3e, $00, $dc, $81, $00, $7f
lf9a6           .byte $b1, $87, $10, $97, $17, $cb, $80, $16
                .byte $c2, $86, $7e, $cb, $80, $15, $c2, $86
                .byte $7e, $7f
lf9b8           .byte $b1, $81, $19, $c2, $83, $7e, $81, $00
                .byte $83, $14, $08, $87, $01, $83, $08, $93
                .byte $13, $87, $18, $83, $13, $80, $0f, $c2
                .byte $81, $7e, $80, $00, $e1, $0c, $c2, $84
                .byte $7e, $00, $80, $7e, $83, $18, $7f
lf9df           .byte $80, $00, $ac, $81, $35, $e3, $80, $7e
                .byte $00, $cb, $81, $00, $80, $7e, $81, $00
                .byte $80, $7e, $82, $00, $ed, $80, $31, $c2
                .byte $82, $7e, $c3, $85, $7e, $c2, $84, $7e
                .byte $ea, $81, $00, $b5, $80, $00, $e1, $37
                .byte $c2, $83, $7e, $c3, $86, $7e, $c2, $82
                .byte $7e, $e5, $80, $7e, $92, $3a, $c2, $81
                .byte $7e, $e5, $80, $7e, $91, $37, $ac, $85
                .byte $37, $81, $00, $7f
lfa23           .byte $a2, $8f, $05, $8e, $7e, $80, $00, $8f
                .byte $03, $8e, $7e, $80, $00, $7f
lfa31           .byte $8f, $01, $8e, $7e, $80, $00, $8e, $0f
                .byte $80, $00, $8e, $03, $80, $00, $7f
lfa40           .byte $a3, $83, $20, $81, $20, $80, $20, $20
                .byte $83, $20, $81, $20, $82, $20, $80, $00
                .byte $a3, $20, $20, $81, $20, $20, $20, $20
                .byte $80, $20, $20, $81, $20, $a4, $83, $1f
                .byte $81, $1f, $1f, $83, $1f, $81, $1f, $83
                .byte $1f, $80, $1f, $1f, $81, $1f, $a4, $1f
                .byte $1f, $1f, $80, $1f, $1f, $81, $1f, $7f
lfa78           .byte $ce, $80, $20, $e2, $7e, $00, $e3, $83
                .byte $00, $7e, $00, $e5, $80, $00, $90, $29
                .byte $82, $7e, $e1, $80, $7e, $c2, $85, $00
                .byte $e3, $83, $00, $e5, $80, $00, $90, $2e
                .byte $82, $7e, $c3, $80, $7e, $e1, $88, $00
                .byte $90, $2c, $90, $2b, $90, $27, $82, $7e
                .byte $d6, $80, $7e, $81, $00, $c3, $82, $00
                .byte $cb, $84, $00, $d5, $80, $00, $7f
lfab7           .byte $b1, $8f, $0d, $92, $19, $c2, $81, $7e
                .byte $8a, $00, $80, $01, $88, $00, $d5, $81
                .byte $00, $cb, $83, $00, $7f
lfacc           .byte $80, $00, $d5, $00, $a2, $05, $00, $7f
lfad4           .byte $81, $7e, $a3, $1b, $7f
lfad9           .byte $81, $7e, $a1, $80, $11, $00, $7f
lfae0           .byte $ce, $80, $20, $e2, $7e, $00, $e3, $83
                .byte $00, $e3, $7e, $80, $00, $e5, $00, $a7
                .byte $00, $90, $1b, $81, $1d, $c2, $80, $7e
                .byte $86, $00, $e3, $85, $00, $e5, $80, $00
                .byte $a7, $84, $22, $c3, $7e, $c2, $80, $7e
                .byte $82, $00, $90, $20, $90, $1f, $90, $1b
                .byte $81, $7e, $d6, $80, $7e, $c2, $7e, $82
                .byte $00, $93, $18, $cb, $80, $00, $c2, $81
                .byte $00, $d5, $80, $00, $7f
lfb25           .byte $ca, $80, $3e, $92, $41, $c3, $8c, $7e
                .byte $82, $00, $ba, $81, $18, $ec, $00, $20
                .byte $ec, $00, $24, $80, $3c, $00, $ba, $81
                .byte $46, $91, $48, $44, $90, $43, $c3, $82
                .byte $7e, $91, $3f, $91, $38, $90, $37, $c3
                .byte $83, $7e, $82, $00, $ba, $81, $1d, $80
                .byte $1f, $00, $81, $1b, $80, $20, $00, $1f
                .byte $00, $7f
lfb5f           .byte $c2, $87, $00, $80, $42, $00, $c2, $85
                .byte $00, $80, $40, $00, $c2, $85, $00, $80
                .byte $3f, $c2, $83, $00, $dd, $82, $7e, $7f
lfb77           .byte $b2, $80, $08, $08, $a2, $81, $08, $00
                .byte $80, $08, $b2, $08, $a2, $81, $0a, $00
                .byte $a2, $0a, $b2, $80, $05, $00, $7f
lfb8e           .byte $b7, $80, $20, $20, $83, $20, $80, $20
                .byte $20, $83, $20, $81, $20, $14, $7f
lfb9d           .byte $a1, $80, $43, $90, $44, $91, $43, $91
                .byte $41, $92, $3c, $c3, $87, $7e, $82, $00
                .byte $ba, $81, $19, $ec, $00, $1d, $ec, $00
                .byte $20, $80, $3f, $00, $a1, $81, $4b, $91
                .byte $46, $91, $44, $90, $43, $c3, $82, $7e
                .byte $91, $3f, $91, $38, $90, $37, $c3, $84
                .byte $7e, $81, $00, $ba, $22, $80, $1f, $00
                .byte $81, $1d, $80, $1b, $c3, $82, $7e, $7f
lfbdd           .byte $a1, $83, $3c, $c3, $7e, $93, $41, $c3
                .byte $84, $7e, $82, $00, $ba, $81, $18, $ec
                .byte $00, $20, $ec, $00, $24, $ba, $30, $80
                .byte $38, $90, $3a, $81, $33, $3c, $a1, $83
                .byte $3a, $c3, $87, $7e, $81, $00, $ba, $24
                .byte $ec, $00, $20, $ec, $00, $1f, $ec, $00
                .byte $7f
lfc0e           .byte $a1, $80, $43, $90, $44, $91, $43, $91
                .byte $41, $90, $3c, $c3, $82, $7e, $91, $38
                .byte $91, $37, $90, $35, $c3, $83, $7e, $80
                .byte $00, $ba, $81, $19, $ec, $00, $1d, $ec
                .byte $00, $80, $20, $00, $3a, $00, $a1, $81
                .byte $4b, $91, $46, $91, $44, $90, $43, $c3
                .byte $82, $7e, $91, $3a, $91, $38, $90, $37
                .byte $c3, $84, $7e, $81, $00, $ba, $22, $80
                .byte $1f, $00, $81, $1d, $80, $1b, $c3, $81
                .byte $7e, $80, $00, $7f
lfc5a           .byte $b7, $80, $2c, $2c, $81, $2c, $20, $80
                .byte $20, $20, $83, $2c, $81, $20, $ac, $80
                .byte $29, $f0, $82, $7e, $f0, $81, $29, $b7
                .byte $20, $20, $20, $20, $80, $20, $20, $81
                .byte $20, $b8, $83, $1f, $81, $1f, $1f, $83
                .byte $1f, $ad, $81, $1d, $b8, $83, $1f, $80
                .byte $1f, $1f, $81, $1f, $1f, $1f, $1f, $80
                .byte $1f, $1f, $81, $1f, $7f
lfc97           .byte $a4, $80, $29, $29, $81, $29, $1d, $80
                .byte $1d, $1d, $83, $29, $81, $1d, $83, $29
                .byte $80, $1d, $1d, $81, $1d, $1d, $80, $1d
                .byte $1d, $81, $1d, $80, $1d, $1d, $81, $29
                .byte $80, $2b, $2b, $81, $2b, $1f, $1f, $83
                .byte $2b, $81, $1f, $83, $2b, $80, $1f, $1f
                .byte $81, $1f, $1f, $80, $1f, $1f, $81, $1f
                .byte $80, $1f, $1f, $81, $1f, $7f
lfcd5           .byte $b7, $80, $20, $20, $81, $20, $20, $80
                .byte $20, $20, $83, $20, $81, $20, $ac, $29
                .byte $f0, $7e, $f0, $35, $b7, $20, $20, $80
                .byte $20, $20, $81, $20, $80, $20, $20, $81
                .byte $20, $b8, $83, $1f, $81, $1f, $1f, $83
                .byte $1f, $ad, $81, $1d, $b8, $83, $1f, $80
                .byte $1f, $1f, $81, $1f, $1f, $80, $1f, $1f
                .byte $81, $1f, $80, $1f, $1f, $81, $1f, $7f
lfd15           .byte $b7, $80, $2c, $2c, $81, $2c, $20, $80
                .byte $20, $20, $83, $2c, $81, $20, $2c, $ac
                .byte $80, $7e, $f0, $82, $35, $b7, $81, $20
                .byte $20, $20, $20, $80, $20, $2c, $81, $2c
                .byte $bb, $80, $2e, $2e, $81, $2e, $22, $80
                .byte $22, $22, $83, $2e, $ad, $81, $1d, $bb
                .byte $83, $2e, $b8, $80, $1f, $1f, $81, $1f
                .byte $1f, $1f, $1f, $80, $1f, $1f, $81, $1f
                .byte $7f
