; This file was automatically generated by SIDdecompiler 0.8 from 'sid/Space_Moguls_Ingame.sid'
; Name:      Whistler
; Author:    Stein Pedersen
; Released:  (C) 2018 Prosonix
; Subtunes:  1

                * = $1000

init            jmp l3d29
play            jmp l2c32
                .byte $4c, $63, $3d, $4c, $74, $3d, $4c, $fb
                .byte $3c, $4c, $fb, $3c
l2c12           .byte $d0
l2c13           .byte $22
l2c14           .byte $55
l2c15           .byte $55
l2c16           .byte $10
l2c17           .byte $07
l2c18           .byte $b9
l2c19           .byte $68
l2c1a           .byte $11
l2c1b           .byte $44
l2c1c           .byte $44
l2c1d           .byte $20
l2c1e           .byte $d2
l2c1f           .byte $8e
l2c20           .byte $43
l2c21           .byte $03
l2c22           .byte $e5
l2c23           .byte $e5
l2c24           .byte $41
l2c25           .byte $04
l2c26           .byte $a9
l2c27           .byte $00
l2c28           .byte $75
l2c29           .byte $f2
l2c2a           .byte $1f, $00, $00, $00, $00, $00, $00, $00
l2c32           lda l2c17
                sta $d405
                lda l2c18
                sta $d406
                lda l2c1e
                sta $d40c
                lda l2c1f
                sta $d40d
                lda l2c25
                sta $d413
                lda l2c26
                sta $d414
                lda l2c14
                sta $d402
                lda l2c15
                sta $d403
                lda l2c12
                sta $d400
                lda l2c13
                sta $d401
                lda l2c1b
                sta $d409
                lda l2c1c
                sta $d40a
                lda l2c19
                sta $d407
                lda l2c1a
                sta $d408
                lda l2c22
                sta $d410
                lda l2c23
                sta $d411
                lda l2c20
                sta $d40e
                lda l2c21
                sta $d40f
                lda l2c27
                sta $d415
                lda l2c28
                sta $d416
                lda l2c2a
                sta $d418
                lda l2c29
                sta $d417
                lda l2c16
                sta $d404
                lda l2c1d
                sta $d40b
                lda l2c24
                sta $d412
l2cc9           lda #$00
                beq l2cd3
                bpl l2ccf
                .byte $60
l2ccf           jmp l3cfc
l2cd3           lda #$00
                beq l2cfc
                .byte $a9, $00, $f0, $15, $ce, $d7, $2c, $4c
                .byte $fc, $2c, $2c, $d3, $2c, $10, $03, $4c
                .byte $06, $2c, $a9, $00, $8d, $d3, $2c, $f0
                .byte $0d, $ad, $3e, $32, $f0, $ec, $ce, $3e
                .byte $32, $a9, $00, $8d, $d7, $2c
l2cfc           dec l2d18+1
                bpl l2d06
l2d02           lda #$05
                sta l2d18+1
l2d06           ldx #$02
l2d08           stx $04
                ldy l3397,X
                sty $05
                lda #$00
                sta l3214+1
                sta l321b+1
l2d18           lda #$01
                cmp l2d02+1
                bne l2d23
                dec l33aa,X
                bmi l2d26
l2d23           jmp l2e62
l2d26           lda l371b,X
                sta $02
                lda l371e,X
                sta $03
l2d30           ldy l33c8,X
                lda ($02),Y
                cmp #$a0
                bcc l2d6e
                cmp #$ff
                bne l2d4b
                iny 
                lda ($02),Y
                sta l33c8,X
                lda #$00
                sta l3394,X
                jmp l2d30
l2d4b           cmp #$fe
                bne l2d58
                .byte $4c, $06, $2c, $fe, $c8, $33, $4c, $30
                .byte $2d
l2d58           cmp #$c0
                bcc l2d6e
                sec 
                sbc #$e0
                sta l3394,X
                inc l33c8,X
                iny 
                lda ($02),Y
                cmp #$a0
                bcc l2d6e
                .byte $b0, $cb
l2d6e           tay 
                lda l377b,Y
                clc 
                adc l340d,X
                sta $02
                lda l37a5,Y
                adc l3410,X
                sta $03
                lda #$ff
                sta l33f8,X
                lda #$00
                sta l33fe,X
                lda #$1b
                sta l3401,X
                ldy #$00
                lda ($02),Y
                bpl l2dbb
                cmp #$c0
                bcc l2db3
                cmp #$e0
                and #$1f
                sta l33ad,X
                bcc l2dae
l2da2           lda #$01
                sta l33fe,X
                lda #$18
                sta l3401,X
                bpl l2dff
l2dae           iny 
                lda ($02),Y
                bpl l2dbb
l2db3           and #$3f
                sta l33f8,X
                iny 
                lda ($02),Y
l2dbb           cmp #$60
                bcc l2df8
                and #$1f
                asl 
                sta l2dc6+1
l2dc6           bpl l2dc7
l2dc7           bpl l2ddf
                .byte $10, $09
                bpl l2dea
                lda #$01
                sta l33fe,X
                bne l2df5
                .byte $bd, $a4, $33, $09, $01, $9d, $a4, $33
                .byte $4c, $a2, $2d
l2ddf           lda l33a4,X
                and #$fe
                sta l33a4,X
                jmp l2da2
l2dea           iny 
                lda ($02),Y
                sta l3391,X
                lda #$81
                sta l33fe,X
l2df5           iny 
                lda ($02),Y
l2df8           clc 
                adc l3394,X
                sta l33fb,X
l2dff           iny 
                lda ($02),Y
                bne l2e10
                inc l33c8,X
                sta l340d,X
                sta l3410,X
                jmp l2e20
l2e10           tya 
                clc 
                adc l340d,X
                sta l340d,X
                lda #$00
                adc l3410,X
                sta l3410,X
l2e20           lda l33ad,X
                sta l33aa,X
                lda l33fe,X
                bne l2e5f
                ldy l33f8,X
                bpl l2e35
                ldy l33c5,X
                bpl l2e3c
l2e35           cpy #$20
                bcc l2e3c
                ldy l33d7,X
l2e3c           lda l362b,Y
                sta l2e43+1
l2e43           bpl l2e5f
                lda #$02
                bne l2e4a
                lda #$00
l2e4a           ldy $05
                sta l2c18,Y
                lda #$0f
                sta l2c17,Y
                lda l33a4,X
                and #$fe
                sta l33a4,X
                jmp l3228
l2e5f           jmp l2f74
l2e62           lda l3401,X
                sta l2e69+1
l2e69           bpl l2e82
                lda #$18
                sta l3401,X
                ldy l33c5,X
                ldx $05
                lda l368b,Y
                sta l2c17,X
                lda l36a3,Y
                sta l2c18,X
                ldx $04
l2e82           jmp l2f74
                lda l33fe,X
                sta $02
                beq l2e97
                lda #$18
                sta l3401,X
                ldy l33c5,X
                jmp l2ef5
l2e97           lda #$00
                sta l3401,X
                lda l33f8,X
                bmi l2ed1
                and #$3f
                cmp #$20
                bcc l2eb8
                and #$1f
                tay 
                lda l361f,Y
                sta l33ef,X
                lda l33d7,X
                sta l33c5,X
                bpl l2ed1
l2eb8           sta l33c5,X
                tay 
                lda l3643,Y
                beq l2ed1
                sta l33f5,X
                sta l33f2,X
                tya 
                sta l33d7,X
                lda l365b,Y
                sta l33ef,X
l2ed1           ldy l33c5,X
                lda l3607,Y
                sta l33ec,X
                lda l33c5,X
                sta l33b0,X
                tay 
                lda l3575,Y
                sta l33da,X
                lda l3461,Y
                sta l33e3,X
                lda l34c3,Y
                sta l33e9,X
                ldx $04
l2ef5           lda l33fb,X
                sta l339a
                lda l36bb,Y
                sta l33b3,X
                clc 
                lda l36eb,Y
                bpl l2f0a
                .byte $38, $29, $7f
l2f0a           ror 
                sta l33b6,X
                asl 
                sta l3407,X
                lda l3673,Y
                beq l2f30
                .byte $c9, $40, $b0, $15, $a9, $00, $9d, $0a
                .byte $34, $b9, $eb, $36, $0a, $7d, $07, $34
                .byte $9d, $07, $34, $9d, $04, $34, $4c, $3b
                .byte $2f
l2f30           lda l36d3,Y
                sta l340a,X
                lda #$ff
                sta l3404,X
                ldy l339a
                lda l328f,Y
                sta l33bf,X
                lda l332b,Y
                sta l33c2,X
                bit $02
                bpl l2f5c
                tya 
                cmp l33d4,X
                bcs l2f56+1
                lda #$80
l2f56           bit $01a9
                jmp l2f6a
l2f5c           lda l33c2,X
                sta l33bc,X
                lda l33bf,X
                sta l33b9,X
                lda #$00
l2f6a           sta l339e,X
                tya 
                sta l33d4,X
                jmp l3228
l2f74           ldy l33da,X
                lda l34db,Y
                sta l2f7e+1
l2f7e           bpl l2fa3
                lda l3528,Y
                sta l33dd,X
                inc l33da,X
                bne l2fa3
                dec l33dd,X
                bne l2fa3
                inc l33da,X
                bne l2fa3
                .byte $b9, $28, $35, $a8
                lda l3528,Y
                sta l33a4,X
                iny 
                tya 
                sta l33da,X
l2fa3           ldy l33e3,X
                lda l3413,Y
                sta l2fad+1
l2fad           bpl l2fde
                lda l343a,Y
                sta l33e3,X
                jmp l2ff2
                lda l343a,Y
                sta l33a7,X
                jmp l2fef
                lda l343a,Y
                sta l33e0,X
                inc l33e3,X
                bne l2ff2
                sec 
                lda l33a7,X
                sbc l343a,Y
                sbc #$00
                sta l33a7,X
                dec l33e0,X
                bpl l2ff2
                bmi l2fef
l2fde           clc 
                lda l33a7,X
                adc l343a,Y
                adc #$00
                sta l33a7,X
                dec l33e0,X
                bpl l2ff2
l2fef           inc l33e3,X
l2ff2           ldy l33e9,X
                lda l3479,Y
                sta l2ffc+1
l2ffc           bpl l305e
                lda l3237+1
                ora l338b,X
                sta l3237+1
                lda l349e,Y
                sta l3240+1
                iny 
                lda l349e,Y
                sta l33a1,X
                sta l3245+1
                iny 
                tya 
                sta l33e9,X
                bne l305e
                lda l3237+1
                and l338e,X
                sta l3237+1
                jmp l305b
                lda l349e,Y
                sta l33e9,X
                lda l33a1,X
                sta l3245+1
                jmp l305e
                lda l349e,Y
                sta l33e6,X
                lda l33a1,X
                sta l3245+1
                inc l33e9,X
                bne l305e
                clc 
                lda l33a1,X
                adc l349e,Y
                sta l33a1,X
                sta l3245+1
                dec l33e6,X
                bpl l305e
l305b           inc l33e9,X
l305e           ldy l33ec,X
l3061           lda l358d,Y
                sta l3068+1
l3068           bpl l30ab
                lda l35ca,Y
                sta l33ec,X
                tay 
                jmp l3061
                lda l33ef,X
                sta l33ec,X
                tay 
                jmp l3061
                dec l33f2,X
                bne l308b
                lda l33f5,X
                sta l33f2,X
                inc l33ec,X
l308b           lda l35ca,Y
                jmp l30ad
                inc l33ec,X
                lda l35ca,Y
                tax 
                ldy $05
                lda l328f,X
                sta l2c12,Y
                lda l332b,X
                sta l2c13,Y
                ldx $04
                jmp l321f
l30ab           lda #$00
l30ad           clc 
                adc l33d4,X
                tay 
                lda l33d4,X
                tax 
                lda l328f,Y
                sec 
                sbc l328f,X
                sta $02
                lda l332b,Y
                sbc l332b,X
                ldx $04
                sta l33ce,X
                lda $02
                sta l33cb,X
                ldy l33b0,X
                lda l3703,Y
                beq l30e9
                .byte $a8, $38, $a9, $00, $f9, $53, $32, $8d
                .byte $14, $32, $a9, $00, $f9, $ef, $32, $8d
                .byte $1b, $32
l30e9           ldy l33b0,X
                lda l339e,X
                beq l30f4
                jmp l318e
l30f4           lda l36d3,Y
                bne l30fc
                jmp l318b
l30fc           lda l33b3,X
                beq l3107
                dec l33b3,X
                jmp l318b
l3107           lda l3404,X
                bmi l3130
                dec l3404,X
                bpl l3130
                lda l340a,X
                clc 
                adc l3673,Y
                sta l340a,X
                cmp l36d3,Y
                bcc l312a
                .byte $b9, $d3, $36, $9d, $0a, $34, $a9, $ff
                .byte $30, $03
l312a           lda l3407,X
                sta l3404,X
l3130           lda l33d4,X
                lsr 
                clc 
                adc l340a,X
                tay 
                lda l3253,Y
                sta l317f+1
                lda l32ef,Y
                sta l3187+1
                ldy l33b0,X
                lda l33b6,X
                bmi l3160
                dec l33b6,X
                bpl l315a
                lda #$80
                ora l36eb,Y
                sta l33b6,X
l315a           ldy #$18
                lda #$69
                bne l3171
l3160           dec l33b6,X
                bmi l316d
                lda l36eb,Y
                and #$7f
                sta l33b6,X
l316d           ldy #$38
                lda #$e9
l3171           sty l317d
                sta l317f
                sta l3187
                lda l33b9,X
l317d           clc 
l317f           adc #$1a
                sta l33b9,X
                lda l33bc,X
l3187           adc #$00
                sta l33bc,X
l318b           jmp l31fd
l318e           php 
                lda #$00
                sta $03
                lda l3391,X
                asl 
                rol $03
                asl 
                rol $03
                sta $02
                plp 
                bmi l31dd
                lda l339e,X
                bmi l31dd
                lda l33b9,X
                clc 
                adc $02
                sta l33b9,X
                lda $03
                adc l33bc,X
                sta l33bc,X
                lda l33c2,X
                cmp l33bc,X
                bcc l31c9
                bne l31fd
                lda l33bf,X
                cmp l33b9,X
                bcs l31fd
l31c9           lda l33bf,X
                sta l33b9,X
                lda l33c2,X
                sta l33bc,X
                lda #$00
                sta l339e,X
                jmp l31fd
l31dd           sec 
                lda l33b9,X
                sbc $02
                sta l33b9,X
                lda l33bc,X
                sbc $03
                sta l33bc,X
                cmp l33c2,X
                bcc l31c9
                bne l31fd
                lda l33bf,X
                cmp l33b9,X
                bcs l31c9
l31fd           ldy $05
                lda l33b9,X
                clc 
                adc l33cb,X
                sta $02
                lda l33bc,X
                adc l33ce,X
                sta $03
                clc 
                lda $02
l3214           adc #$00
                sta l2c12,Y
                lda $03
l321b           adc #$00
                sta l2c13,Y
l321f           lda l33a7,X
                sta l2c14,Y
                sta l2c15,Y
l3228           lda l33a4,X
                ldy $05
                sta l2c16,Y
                dex 
                bmi l3237
                jmp l2d08
l3237           lda #$02
                ora #$f0
                sta l2c29
l323e           lda #$0f
l3240           ora #$10
                sta l2c2a
l3245           lda #$75
                sta l2c28
                rts 
                .byte $00, $00, $00, $07, $07, $07, $0e, $0e
                .byte $0e
l3253           .byte $00, $01, $02, $03, $04, $05, $06, $07
                .byte $09, $0b, $0d, $0f, $11, $12, $13, $14
                .byte $15, $17, $18, $1a, $1b, $1d, $1f, $20
                .byte $22, $24, $27, $29, $2b, $2e, $31, $34
                .byte $37, $3a, $3e, $41, $45, $49, $4e, $52
                .byte $57, $5d, $62, $68, $6e, $75, $7c, $83
                .byte $8b, $93, $9c, $a5, $af, $ba, $c5, $d0
                .byte $dd, $ea, $f8, $07
l328f           .byte $17, $27, $39, $4b, $5f, $74, $8a, $a1
                .byte $ba, $d4, $f0, $0e, $2d, $4e, $71, $96
                .byte $be, $e8, $14, $43, $74, $a9, $e1, $1c
                .byte $5a, $9c, $e2, $2d, $7c, $cf, $28, $85
                .byte $e8, $52, $c1, $37, $b4, $39, $c5, $5a
                .byte $f7, $9e, $4f, $0a, $d1, $a3, $82, $6e
                .byte $68, $71, $8a, $b3, $ee, $3c, $9e, $15
                .byte $a2, $46, $04, $dc, $d0, $e2, $14, $67
                .byte $dd, $79, $3c, $29, $44, $8d, $08, $b8
                .byte $a1, $c5, $28, $cd, $ba, $f1, $78, $53
                .byte $87, $1a, $10, $71, $42, $89, $4f, $9b
                .byte $74, $e2, $f0, $a6, $0e, $33, $20, $ff
l32ef           .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $01
l332b           .byte $01, $01, $01, $01, $01, $01, $01, $01
                .byte $01, $01, $01, $02, $02, $02, $02, $02
                .byte $02, $02, $03, $03, $03, $03, $03, $04
                .byte $04, $04, $04, $05, $05, $05, $06, $06
                .byte $06, $07, $07, $08, $08, $09, $09, $0a
                .byte $0a, $0b, $0c, $0d, $0d, $0e, $0f, $10
                .byte $11, $12, $13, $14, $15, $17, $18, $1a
                .byte $1b, $1d, $1f, $20, $22, $24, $27, $29
                .byte $2b, $2e, $31, $34, $37, $3a, $3e, $41
                .byte $45, $49, $4e, $52, $57, $5c, $62, $68
                .byte $6e, $75, $7c, $83, $8b, $93, $9c, $a5
                .byte $af, $b9, $c4, $d0, $dd, $ea, $f8, $ff
l338b           .byte $01, $02, $04
l338e           .byte $fe, $fd, $fb
l3391           .byte $00, $08, $00
l3394           .byte $00, $00, $00
l3397           .byte $00, $07, $0e
l339a           .byte $3c, $00, $00, $00
l339e           .byte $00, $00, $00
l33a1           .byte $00, $75, $00
l33a4           .byte $10, $20, $41
l33a7           .byte $55, $44, $e5
l33aa           .byte $01, $08, $00
l33ad           .byte $02, $0f, $01
l33b0           .byte $13, $17, $12
l33b3           .byte $00, $00, $00
l33b6           .byte $00, $00, $00
l33b9           .byte $d0, $9e, $43
l33bc           .byte $22, $0b, $03
l33bf           .byte $d0, $9e, $43
l33c2           .byte $22, $0b, $03
l33c5           .byte $13, $17, $12
l33c8           .byte $17, $12, $1b
l33cb           .byte $00, $ca, $00
l33ce           .byte $00, $05, $00, $00, $00, $00
l33d4           .byte $3c, $29, $13
l33d7           .byte $11, $17, $00
l33da           .byte $05, $4c, $3b
l33dd           .byte $00, $00, $04
l33e0           .byte $08, $09, $08
l33e3           .byte $0b, $00, $1d
l33e6           .byte $00, $53, $00
l33e9           .byte $01, $21, $01
l33ec           .byte $31, $25, $39
l33ef           .byte $05, $23, $00
l33f2           .byte $04, $01, $00
l33f5           .byte $04, $03, $00
l33f8           .byte $ff, $29, $ff
l33fb           .byte $3c, $29, $13
l33fe           .byte $00, $00, $00
l3401           .byte $18, $18, $18
l3404           .byte $ff, $ff, $ff
l3407           .byte $00, $00, $00
l340a           .byte $00, $00, $00
l340d           .byte $80, $15, $08
l3410           .byte $00, $00, $00
l3413           .byte $44, $09, $00, $09, $12, $30, $12, $1d
                .byte $00, $09, $12, $30, $12, $1d, $00, $09
                .byte $12, $30, $12, $1d, $00, $09, $12, $30
                .byte $12, $1d, $00, $09, $12, $30, $12, $1d
                .byte $00, $09, $12, $30, $12, $1d, $00
l343a           .byte $00, $00, $02, $01, $0f, $20, $0f, $20
                .byte $04, $04, $0f, $30, $0f, $30, $0a, $07
                .byte $2b, $30, $2b, $30, $10, $07, $2b, $50
                .byte $2b, $50, $16, $05, $0f, $20, $0f, $20
                .byte $1c, $03, $3f, $20, $3f, $20, $22
l3461           .byte $01, $00, $00, $00, $01, $03, $00, $00
                .byte $00, $09, $09, $00, $03, $00, $0f, $15
                .byte $00, $00, $1b, $09, $21, $21, $21, $00
l3479           .byte $20, $61, $00, $10, $3b, $4c, $3b, $4c
                .byte $2c, $00, $10, $3b, $4c, $3b, $4c, $2c
                .byte $00, $10, $3b, $4c, $3b, $4c, $2c, $00
                .byte $10, $3b, $4c, $3b, $4c, $2c, $00, $10
                .byte $3b, $4c, $3b, $4c, $2c
l349e           .byte $00, $00, $20, $03, $7e, $01, $7e, $ff
                .byte $04, $10, $04, $6f, $02, $6f, $fe, $0b
                .byte $10, $04, $2f, $04, $2f, $fc, $12, $50
                .byte $a0, $4e, $ff, $4e, $01, $19, $10, $a0
                .byte $7e, $ff, $7e, $01, $20
l34c3           .byte $00, $00, $00, $00, $00, $00, $00, $02
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $09, $10, $17, $1e
l34db           .byte $24, $19, $19, $19, $19, $24, $19, $00
                .byte $0b, $19, $24, $19, $24, $19, $19, $19
                .byte $00, $0b, $19, $24, $19, $19, $00, $0b
                .byte $19, $24, $19, $24, $19, $19, $19, $19
                .byte $19, $24, $19, $00, $0b, $19, $24, $19
                .byte $19, $19, $24, $19, $24, $19, $19, $24
                .byte $19, $24, $19, $00, $0b, $19, $24, $19
                .byte $19, $19, $00, $0b, $19, $24, $19, $00
                .byte $0b, $19, $24, $19, $00, $0b, $19, $24
                .byte $19, $00, $0b, $19, $24
l3528           .byte $00, $01, $81, $51, $10, $00, $21, $02
                .byte $00, $20, $00, $11, $00, $01, $81, $41
                .byte $03, $00, $40, $00, $81, $15, $05, $00
                .byte $14, $00, $81, $00, $01, $81, $51, $10
                .byte $10, $00, $81, $01, $00, $80, $00, $01
                .byte $81, $41, $00, $41, $00, $41, $40, $00
                .byte $21, $00, $11, $3e, $00, $10, $00, $01
                .byte $81, $41, $09, $00, $40, $00, $41, $3e
                .byte $00, $40, $00, $41, $1e, $00, $40, $00
                .byte $21, $1e, $00, $20, $00
l3575           .byte $01, $06, $0b, $00, $01, $0d, $14, $1a
                .byte $00, $01, $1c, $22, $27, $06, $2b, $2d
                .byte $30, $32, $37, $01, $3e, $43, $43, $48
l358d           .byte $42, $14, $14, $14, $00, $14, $14, $14
                .byte $00, $14, $14, $14, $00, $14, $14, $14
                .byte $00, $14, $14, $14, $00, $14, $14, $14
                .byte $00, $14, $14, $14, $14, $00, $14, $14
                .byte $14, $14, $00, $14, $14, $14, $14, $00
                .byte $14, $14, $14, $14, $00, $1f, $28, $1f
                .byte $1f, $42, $1f, $0a, $1f, $42, $1f, $28
                .byte $1f, $42, $28, $1f, $0a
l35ca           .byte $00, $07, $03, $00, $01, $07, $04, $00
                .byte $05, $09, $05, $00, $09, $08, $05, $00
                .byte $0d, $00, $03, $08, $11, $00, $03, $05
                .byte $15, $00, $03, $07, $0a, $19, $00, $04
                .byte $07, $09, $1e, $00, $04, $07, $0c, $23
                .byte $00, $03, $07, $0c, $28, $00, $5e, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $5f
                .byte $00, $00, $5f, $00, $00
l3607           .byte $2d, $32, $34, $00, $2d, $36, $3a, $34
                .byte $00, $2d, $2d, $34, $36, $32, $34, $34
                .byte $34, $32, $36, $2d, $34, $34, $34, $32
l361f           .byte $01, $05, $09, $0d, $11, $15, $19, $1e
                .byte $1e, $23, $19, $28
l362b           .byte $04, $1b, $04, $1b, $04, $00, $1b, $04
                .byte $1b, $1b, $1b, $04, $00, $1b, $10, $1b
                .byte $10, $1b, $00, $1b, $04, $04, $10, $1b
l3643           .byte $00, $02, $00, $00, $00, $00, $02, $00
                .byte $00, $00, $00, $00, $00, $02, $00, $00
                .byte $00, $04, $00, $00, $00, $00, $00, $03
l365b           .byte $00, $01, $00, $00, $00, $00, $01, $00
                .byte $00, $00, $00, $00, $00, $01, $00, $00
                .byte $00, $01, $00, $00, $00, $00, $00, $19
l3673           .byte $00, $00, $02, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, $00, $00, $00
l368b           .byte $8a, $01, $8a, $00, $8a, $04, $04, $00
                .byte $24, $04, $00, $02, $04, $02, $03, $00
                .byte $03, $d2, $04, $07, $d0, $d0, $00, $d2
l36a3           .byte $e9, $79, $d8, $29, $e9, $d9, $48, $18
                .byte $48, $a9, $59, $34, $89, $79, $48, $29
                .byte $48, $ad, $a9, $b9, $8d, $8c, $4f, $8e
l36bb           .byte $10, $00, $10, $1c, $18, $00, $00, $00
                .byte $1c, $00, $00, $00, $0c, $00, $10, $10
                .byte $0c, $00, $00, $00, $20, $20, $20, $00
l36d3           .byte $1c, $00, $20, $18, $10, $00, $00, $00
                .byte $21, $00, $00, $00, $18, $00, $40, $40
                .byte $42, $00, $00, $00, $01, $01, $14, $00
l36eb           .byte $83, $00, $83, $04, $83, $00, $00, $00
                .byte $04, $00, $00, $00, $03, $00, $03, $03
                .byte $04, $00, $00, $00, $04, $04, $04, $00
l3703           .byte $00, $00, $00, $28, $00, $00, $00, $00
                .byte $05, $00, $00, $00, $00, $00, $10, $1a
                .byte $10, $00, $00, $00, $00, $00, $00, $00
l371b           .byte <l3721, <l373f, <l3755
l371e           .byte >l3721, >l373f, >l3755
l3721           .byte $10, $10, $10, $10, $10, $1a, $1a, $12
                .byte $12, $12, $12, $1c, $1c, $1c, $12, $12
                .byte $1c, $1c, $25, $25, $24, $24, $25, $25
                .byte $28, $28, $28, $28, $ff, $00
l373f           .byte $11, $11, $11, $11, $11, $1b, $1b, $13
                .byte $13, $1d, $21, $13, $1d, $13, $1d, $13
                .byte $1d, $26, $29, $27, $ff, $00
l3755           .byte $00, $0d, $0d, $de, $0d, $dd, $0d, $dc
                .byte $0d, $e0, $14, $1f, $1e, $22, $20, $23
                .byte $20, $23, $20, $23, $20, $23, $20, $23
                .byte $20, $23, $20, $23, $20, $23, $20, $23
                .byte $20, $23, $20, $23, $ff, $00
l377b           .byte <l37cf, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, <l37d5, $00, $00
                .byte <l37e4, <l3806, <l3828, <l3869, <l389c, $00, $00, $00
                .byte $00, $00, <l38bd, <l38df, <l3901, <l3942, <l3975, <l3996
                .byte <l39b0, <l39ee, <l3a16, <l3a27, <l3a64, <l3b65, <l3c4d, <l3c64
                .byte <l3ccc, <l3cda
l37a5           .byte >l37cf, $00, $00, $00, $00, $00, $00, $00
                .byte $00, $00, $00, $00, $00, >l37d5, $00, $00
                .byte >l37e4, >l3806, >l3828, >l3869, >l389c, $00, $00, $00
                .byte $00, $00, >l38bd, >l38df, >l3901, >l3942, >l3975, >l3996
                .byte >l39b0, >l39ee, >l3a16, >l3a27, >l3a64, >l3b65, >l3c4d, >l3c64
                .byte >l3ccc, >l3cda
l37cf           .byte $cf, $60, $ef, $ef, $ef, $00
l37d5           .byte $c0, $85, $18, $c1, $18, $c0, $18, $c1
                .byte $18, $c0, $18, $cf, $18, $e8, $00
l37e4           .byte $c1, $89, $30, $89, $35, $89, $37, $c3
                .byte $89, $3a, $c1, $89, $30, $89, $35, $89
                .byte $37, $89, $30, $89, $35, $89, $37, $c3
                .byte $89, $3a, $c1, $89, $30, $89, $35, $89
                .byte $37, $00
l3806           .byte $e2, $c1, $8a, $30, $8a, $35, $8a, $37
                .byte $c3, $8a, $3a, $c1, $8a, $30, $8a, $35
                .byte $8a, $37, $8a, $30, $8a, $35, $8a, $37
                .byte $c3, $8a, $3a, $c1, $8a, $30, $c0, $8a
                .byte $35, $00
l3828           .byte $c1, $89, $30, $c0, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3a, $c1, $8a
                .byte $37, $c0, $8a, $3a, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $89, $30, $8a, $37, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3a, $c1, $8a
                .byte $37, $c0, $8a, $3a, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $00
l3869           .byte $c0, $81, $30, $c1, $30, $c0, $30, $c1
                .byte $30, $c0, $30, $c8, $30, $c0, $30, $c1
                .byte $30, $c0, $30, $c1, $30, $c0, $30, $c8
                .byte $30, $c0, $a3, $32, $c1, $32, $c0, $32
                .byte $c1, $32, $c0, $32, $c8, $32, $c0, $32
                .byte $c1, $32, $c0, $32, $c1, $32, $c0, $32
                .byte $c8, $32, $00
l389c           .byte $c9, $85, $18, $c1, $1a, $1b, $1f, $c9
                .byte $18, $c1, $1a, $1b, $1f, $c9, $16, $c1
                .byte $18, $1a, $1d, $c9, $16, $c0, $8c, $1f
                .byte $c1, $63, $20, $c0, $85, $1f, $1e, $1f
                .byte $00
l38bd           .byte $c1, $89, $30, $89, $35, $89, $37, $c3
                .byte $89, $3c, $c1, $89, $30, $89, $35, $89
                .byte $37, $89, $30, $89, $35, $89, $37, $c3
                .byte $89, $3c, $c1, $89, $30, $89, $35, $89
                .byte $37, $00
l38df           .byte $e2, $c1, $8a, $30, $8a, $35, $8a, $37
                .byte $c3, $8a, $3c, $c1, $8a, $30, $8a, $35
                .byte $8a, $37, $8a, $30, $8a, $35, $8a, $37
                .byte $c3, $8a, $3c, $c1, $8a, $30, $c0, $8a
                .byte $35, $00
l3901           .byte $c1, $89, $30, $c0, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3c, $c1, $8a
                .byte $37, $c0, $8a, $3c, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $89, $30, $8a, $37, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3c, $c1, $8a
                .byte $37, $c0, $8a, $3c, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $00
l3942           .byte $c0, $a2, $30, $c1, $30, $c0, $30, $c1
                .byte $30, $c0, $30, $c8, $30, $c0, $30, $c1
                .byte $30, $c0, $30, $c1, $30, $c0, $30, $c8
                .byte $30, $c0, $a4, $30, $c1, $30, $c0, $30
                .byte $c1, $30, $c0, $30, $c8, $30, $c0, $30
                .byte $c1, $30, $c0, $30, $c1, $30, $c0, $30
                .byte $c8, $30, $00
l3975           .byte $c9, $15, $c1, $16, $18, $1b, $c9, $15
                .byte $c1, $16, $18, $1b, $c2, $14, $14, $14
                .byte $14, $14, $c0, $14, $20, $1f, $c2, $20
                .byte $20, $20, $c1, $20, $c0, $1f, $1d, $20
                .byte $00
l3996           .byte $c9, $85, $18, $c1, $1a, $1b, $1f, $c9
                .byte $18, $c1, $1a, $1b, $1f, $c9, $16, $c1
                .byte $18, $1a, $1d, $c9, $16, $c1, $18, $1a
                .byte $1d, $00
l39b0           .byte $c2, $92, $0c, $c0, $18, $60, $16, $c1
                .byte $13, $16, $18, $c0, $11, $13, $c1, $16
                .byte $c2, $0c, $c0, $18, $60, $16, $c1, $13
                .byte $16, $18, $c0, $1b, $18, $16, $18, $c2
                .byte $0a, $c0, $18, $60, $16, $c1, $13, $16
                .byte $18, $c0, $11, $13, $c1, $16, $c2, $0a
                .byte $c0, $18, $60, $16, $c1, $13, $16, $18
                .byte $c0, $1b, $18, $16, $18, $00
l39ee           .byte $c0, $a5, $32, $c1, $32, $c0, $32, $c1
                .byte $32, $c0, $32, $c1, $32, $c0, $32, $c5
                .byte $32, $c0, $a1, $37, $c1, $37, $c0, $37
                .byte $c1, $37, $c0, $37, $c1, $37, $c0, $37
                .byte $c1, $37, $c0, $37, $37, $c1, $37, $00
l3a16           .byte $c2, $1f, $1f, $1f, $1f, $c1, $1f, $1f
                .byte $c2, $1f, $1f, $1f, $1f, $c1, $23, $26
                .byte $00
l3a27           .byte $c2, $09, $c0, $18, $60, $16, $c1, $13
                .byte $16, $18, $c0, $11, $13, $c1, $16, $c2
                .byte $09, $c0, $18, $60, $16, $c1, $13, $16
                .byte $18, $c0, $1b, $18, $16, $18, $c2, $08
                .byte $c0, $18, $60, $16, $c1, $13, $16, $18
                .byte $c0, $11, $13, $c1, $16, $c2, $08, $c0
                .byte $18, $60, $16, $c1, $13, $16, $18, $c0
                .byte $1b, $18, $16, $18, $00
l3a64           .byte $c1, $89, $30, $c0, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3a, $c1, $8a
                .byte $37, $c0, $8a, $3a, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $89, $30, $8a, $37, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3a, $c1, $8a
                .byte $37, $c0, $8a, $3a, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $c1, $89, $30, $c0, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3a, $c1, $8a
                .byte $37, $c0, $8a, $3a, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $89, $30, $8a, $37, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3a, $c1, $8a
                .byte $37, $c0, $8a, $3a, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $c1, $89, $30, $c0, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3c, $c1, $8a
                .byte $37, $c0, $8a, $3c, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $89, $30, $8a, $37, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3c, $c1, $8a
                .byte $37, $c0, $8a, $3c, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $c1, $89, $30, $c0, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3c, $c1, $8a
                .byte $37, $c0, $8a, $3c, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $89, $30, $8a, $37, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $3c, $c1, $8a
                .byte $37, $c0, $8a, $3c, $c1, $89, $30, $c0
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $00
l3b65           .byte $c0, $93, $3c, $3c, $3c, $3c, $3a, $8a
                .byte $35, $93, $3a, $c1, $37, $c0, $8a, $3a
                .byte $c1, $89, $30, $c0, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $89, $30, $8a, $37
                .byte $89, $35, $8a, $30, $89, $37, $8a, $35
                .byte $89, $3a, $c1, $8a, $37, $c0, $8a, $3a
                .byte $c1, $89, $30, $c0, $89, $35, $8a, $30
                .byte $89, $37, $8a, $35, $93, $3c, $3c, $3c
                .byte $3c, $3e, $8a, $35, $93, $3a, $c1, $37
                .byte $c0, $8a, $3a, $c1, $89, $30, $c0, $89
                .byte $35, $8a, $30, $89, $37, $8a, $35, $89
                .byte $30, $8a, $37, $89, $35, $8a, $30, $89
                .byte $37, $8a, $35, $89, $3a, $c1, $8a, $37
                .byte $c0, $8a, $3a, $c1, $89, $30, $c0, $89
                .byte $35, $8a, $30, $89, $37, $8a, $35, $93
                .byte $41, $43, $41, $3c, $43, $41, $c2, $3c
                .byte $c0, $8a, $3c, $c1, $89, $30, $c0, $89
                .byte $35, $8a, $30, $89, $37, $8a, $35, $89
                .byte $30, $8a, $37, $89, $35, $8a, $30, $89
                .byte $37, $8a, $35, $89, $3c, $c1, $8a, $37
                .byte $c0, $8a, $3c, $c1, $89, $30, $c0, $89
                .byte $35, $8a, $30, $89, $37, $8a, $35, $93
                .byte $41, $43, $41, $3c, $43, $41, $c2, $3c
                .byte $c0, $8a, $3c, $c1, $89, $30, $c0, $89
                .byte $35, $8a, $30, $89, $37, $8a, $35, $89
                .byte $30, $8a, $37, $89, $35, $8a, $30, $89
                .byte $37, $8a, $35, $89, $3c, $c1, $8a, $37
                .byte $c0, $8a, $3c, $c1, $89, $30, $c0, $89
                .byte $35, $8a, $30, $89, $37, $8a, $35, $00
l3c4d           .byte $cf, $94, $30, $ef, $32, $ef, $35, $ef
                .byte $33, $ef, $32, $e7, $95, $2e, $cf, $30
                .byte $ef, $94, $24, $ef, $ef, $ef, $00
l3c64           .byte $cf, $96, $3c, $e7, $c3, $62, $10, $3a
                .byte $c1, $3a, $62, $20, $37, $cf, $37, $eb
                .byte $c3, $35, $c5, $30, $c1, $37, $cf, $37
                .byte $e3, $c1, $35, $62, $10, $30, $cf, $32
                .byte $e7, $c3, $2e, $62, $08, $30, $cf, $30
                .byte $ef, $ef, $ef, $ef, $ef, $ef, $e7, $c3
                .byte $37, $62, $10, $3c, $cf, $3c, $e7, $c3
                .byte $3e, $62, $30, $3a, $cf, $37, $eb, $c3
                .byte $62, $20, $35, $c0, $30, $37, $35, $30
                .byte $37, $35, $cf, $30, $e9, $c0, $30, $37
                .byte $35, $30, $37, $35, $cd, $30, $c3, $62
                .byte $04, $2e, $2e, $62, $08, $30, $cf, $30
                .byte $ef, $ef, $ef, $ef, $ef, $ef, $ef, $00
l3ccc           .byte $cf, $91, $3c, $ef, $a1, $3a, $ef, $a4
                .byte $39, $ef, $a1, $38, $ef, $00
l3cda           .byte $cf, $97, $30, $ef, $a7, $2e, $ef, $a9
                .byte $29, $ef, $aa, $35, $ef, $ab, $30, $ef
                .byte $a7, $2e, $ef, $a9, $29, $ef, $aa, $29
                .byte $e7, $c3, $96, $37, $62, $10, $3c, $00
                .byte $05, $60
l3cfc           dec l2cc9+1
                bne l3d26
                ldx #$02
                lda #$00
l3d05           sta l33aa,X
                sta l3394,X
                sta l33c8,X
                sta l340d,X
                sta l3410,X
                sta l339e,X
                sta l33a4,X
                sta l33b0,X
                dex 
                bpl l3d05
                sta l2d18+1
                sta l2cd3+1
l3d26           lda #$00
                rts 
l3d29           lda #$05
                sta l2d02+1
                lda #$01
                sta l2cc9+1
                lda #$00
                ldx #$16
l3d37           sta l2c12,X
                dex 
                bpl l3d37
                lda #$00
                sta l3237+1
                ldx #$03
l3d44           sta l33c8,X
                sta l33aa,X
                dex 
                bpl l3d44
                sta l2d18+1
                sta l2cd3+1
                lda #$f0
                sta l2c29
                lda #$0f
                sta l323e+1
                lda #$10
                sta l3240+1
                rts 
